package main

import (
	"bytes"
	"context"
	"image"
	"image/color"
	"image/gif"
	"image/jpeg"
	"image/png"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"team4s.v3/backend/internal/testsupport"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/require"
)

// openDisplayBackfillFixture extends the shared Phase-117 fixture (minimal media_assets/
// fansub_groups stand-ins already present there, see testsupport.OpenPhase117Postgres) with the
// real media_files table (migration 0026 shape + the status column from migration 0059) and the
// extra media_assets/fansub_groups columns this plan's backfill reads/writes -- identical
// extension style to cmd/migrate-preview-backfill/backfill_test.go's openBackfillTestFixture,
// which proves the exact same "extend a shared isolated-schema fixture" pattern from the
// render-worker side.
func openDisplayBackfillFixture(t *testing.T) *pgxpool.Pool {
	t.Helper()
	pool := testsupport.OpenPhase117Postgres(t)
	ctx := context.Background()
	_, err := pool.Exec(ctx, `
ALTER TABLE media_assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE media_assets
    ADD COLUMN mime_type TEXT,
    ADD COLUMN format TEXT,
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ready',
    ADD COLUMN owner_member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE TABLE media_files (
    id BIGSERIAL PRIMARY KEY,
    media_id BIGINT NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
    variant VARCHAR(50),
    path TEXT NOT NULL,
    width INTEGER,
    height INTEGER,
    size BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'ready',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_media_files_media ON media_files(media_id);

ALTER TABLE fansub_groups ADD COLUMN logo_id BIGINT REFERENCES media_assets(id);
ALTER TABLE fansub_groups ADD COLUMN banner_id BIGINT REFERENCES media_assets(id);

CREATE TABLE fansub_group_media (
    group_id BIGINT NOT NULL REFERENCES fansub_groups(id),
    media_id BIGINT NOT NULL REFERENCES media_assets(id),
    PRIMARY KEY (group_id, media_id)
);
`)
	require.NoError(t, err)
	return pool
}

// insertMediaAsset inserts a media_assets row and returns its generated id. ownerMemberID may be
// nil (the common case for non-story-image assets).
func insertMediaAsset(t *testing.T, pool *pgxpool.Pool, filePath, mimeType string, ownerMemberID *int64) int64 {
	t.Helper()
	var id int64
	err := pool.QueryRow(context.Background(), `
		INSERT INTO media_assets (file_path, mime_type, format, status, owner_member_id, created_at)
		VALUES ($1, $2, 'image', 'ready', $3, NOW())
		RETURNING id
	`, filePath, mimeType, ownerMemberID).Scan(&id)
	require.NoError(t, err)
	return id
}

// insertMediaFile inserts a media_files row for an already-created asset.
func insertMediaFile(t *testing.T, pool *pgxpool.Pool, mediaID int64, variant, path string, width, height int, size int64) int64 {
	t.Helper()
	var id int64
	err := pool.QueryRow(context.Background(), `
		INSERT INTO media_files (media_id, variant, path, width, height, size, status)
		VALUES ($1, $2, $3, $4, $5, $6, 'ready')
		RETURNING id
	`, mediaID, variant, path, width, height, size).Scan(&id)
	require.NoError(t, err)
	return id
}

// insertMember inserts a minimal members row (needed as the FK target for owner_member_id).
func insertMember(t *testing.T, pool *pgxpool.Pool, id int64, nickname string) {
	t.Helper()
	_, err := pool.Exec(context.Background(), `INSERT INTO members (id, nickname) VALUES ($1, $2)`, id, nickname)
	require.NoError(t, err)
}

// insertFansubGroup inserts a minimal fansub_groups row (id is an explicit BIGINT PRIMARY KEY in
// this fixture, not auto-generated, matching testsupport.OpenPhase117Postgres's stand-in table).
func insertFansubGroup(t *testing.T, pool *pgxpool.Pool, id int64, name string) {
	t.Helper()
	_, err := pool.Exec(context.Background(), `INSERT INTO fansub_groups (id, name) VALUES ($1, $2)`, id, name)
	require.NoError(t, err)
}

func setFansubGroupLogo(t *testing.T, pool *pgxpool.Pool, groupID, mediaID int64) {
	t.Helper()
	_, err := pool.Exec(context.Background(), `UPDATE fansub_groups SET logo_id = $1 WHERE id = $2`, mediaID, groupID)
	require.NoError(t, err)
}

func insertFansubGroupMedia(t *testing.T, pool *pgxpool.Pool, groupID, mediaID int64) {
	t.Helper()
	_, err := pool.Exec(context.Background(), `INSERT INTO fansub_group_media (group_id, media_id) VALUES ($1, $2)`, groupID, mediaID)
	require.NoError(t, err)
}

// writeTestFile writes data to dir/name and returns the absolute path.
func writeTestFile(t *testing.T, dir, name string, data []byte) string {
	t.Helper()
	path := filepath.Join(dir, name)
	require.NoError(t, os.WriteFile(path, data, 0o644))
	return path
}

// newStaticJPEGBytes returns an opaque solid-color JPEG of the given size.
func newStaticJPEGBytes(t *testing.T, width, height int) []byte {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			img.Set(x, y, color.RGBA{R: 200, G: 50, B: 50, A: 255})
		}
	}
	var buf bytes.Buffer
	require.NoError(t, jpeg.Encode(&buf, img, &jpeg.Options{Quality: 90}))
	return buf.Bytes()
}

// newTransparentPNGBytes returns a PNG with a visible alpha channel (half-transparent) -- used
// to prove D-18's "transparent sources stay PNG" posture through the backfill path.
func newTransparentPNGBytes(t *testing.T, width, height int) []byte {
	t.Helper()
	img := image.NewNRGBA(image.Rect(0, 0, width, height))
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			img.Set(x, y, color.NRGBA{R: 10, G: 200, B: 10, A: 128})
		}
	}
	var buf bytes.Buffer
	require.NoError(t, png.Encode(&buf, img))
	return buf.Bytes()
}

// newAnimatedGIFBytes returns a 3-frame animated GIF of the given size -- same construction
// style as backend/internal/handlers/media_upload_test.go's newAnimatedGIFBytes (distinct
// package, so duplicated rather than imported across a package boundary that doesn't export it).
func newAnimatedGIFBytes(t *testing.T, width, height int) []byte {
	t.Helper()
	palette := []color.Color{
		color.RGBA{R: 255, A: 255},
		color.RGBA{G: 255, A: 255},
		color.RGBA{B: 255, A: 255},
	}
	anim := &gif.GIF{}
	for frameIdx := range palette {
		frame := image.NewPaletted(image.Rect(0, 0, width, height), palette)
		for y := 0; y < height; y++ {
			for x := 0; x < width; x++ {
				frame.SetColorIndex(x, y, uint8(frameIdx))
			}
		}
		anim.Image = append(anim.Image, frame)
		anim.Delay = append(anim.Delay, 10)
	}
	var buf bytes.Buffer
	require.NoError(t, gif.EncodeAll(&buf, anim))
	return buf.Bytes()
}

// requireFFmpegForBackfillTests resolves an installed ffmpeg binary or fails the test
// immediately -- the animated-GIF display path is proven against REAL ffmpeg, never a mocked
// extractor (established pattern, see segment_render_service_test.go /
// cmd/migrate-preview-backfill/backfill_test.go's requireFFmpegBinary).
func requireFFmpegForBackfillTests(t *testing.T) string {
	t.Helper()
	path, err := exec.LookPath("ffmpeg")
	if err != nil {
		t.Fatal("installed FFmpeg is required for backfill display-variant proof")
	}
	return path
}

// countMediaFilesByVariant returns how many media_files rows exist for mediaID with the given
// variant (0 or 1 expected in every test in this package, but counted rather than assumed so a
// bug that double-inserts is caught instead of silently passing).
func countMediaFilesByVariant(t *testing.T, pool *pgxpool.Pool, mediaID int64, variant string) int {
	t.Helper()
	var count int
	require.NoError(t, pool.QueryRow(context.Background(),
		`SELECT COUNT(*) FROM media_files WHERE media_id = $1 AND variant = $2`, mediaID, variant).Scan(&count))
	return count
}

func displayFilePath(t *testing.T, pool *pgxpool.Pool, mediaID int64) string {
	t.Helper()
	var path string
	require.NoError(t, pool.QueryRow(context.Background(),
		`SELECT path FROM media_files WHERE media_id = $1 AND variant = 'display'`, mediaID).Scan(&path))
	return path
}
