package handlers

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/require"
	"team4s.v3/backend/internal/models"
	"team4s.v3/backend/internal/repository"
	"team4s.v3/backend/internal/testsupport"
)

func TestReleaseMetadataOnlyRejectsSourceSelector(t *testing.T) {
	var input models.EpisodeVersionPatchInput
	require.NoError(t, json.Unmarshal([]byte(`{"title":"A","media_source_id":"source-b"}`), &input))
	require.False(t, isReleaseMetadataOnlyPatch(input))
	valid, message := validateEpisodeVersionPatchRequest(models.EpisodeVersionPatchInput{MediaSourceID: models.OptionalString{Set: true, Value: hydrationText("source-b")}})
	require.Empty(t, message)
	require.True(t, valid.MediaSourceID.Set)
	for _, source := range []*string{nil, hydrationText(""), hydrationText("x,y")} {
		_, message = validateEpisodeVersionPatchRequest(models.EpisodeVersionPatchInput{MediaSourceID: models.OptionalString{Set: true, Value: source}})
		require.NotEmpty(t, message)
	}
}
func hydrationText(s string) *string { return &s }
func openVersionHydrationFixture(t *testing.T) *pgxpool.Pool {
	t.Helper()
	pool := openEVECFixture(t)
	_, err := pool.Exec(context.Background(), `
 ALTER TABLE fansub_releases ADD COLUMN source_id BIGINT,ADD COLUMN source BIGINT,ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(),ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
 ALTER TABLE release_versions ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(),ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
 ALTER TABLE release_variants ADD COLUMN filename TEXT,ADD COLUMN IF NOT EXISTS container TEXT,ADD COLUMN IF NOT EXISTS video_codec TEXT,ADD COLUMN IF NOT EXISTS audio_codec TEXT;
 ALTER TABLE stream_sources ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}',ADD CONSTRAINT uq_stream_sources_provider_external UNIQUE NULLS NOT DISTINCT(provider_type,external_id);
 ALTER TABLE stream_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
 ALTER TABLE release_streams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
 ALTER TABLE release_streams ADD COLUMN stream_type_id BIGINT DEFAULT 1,ADD COLUMN IF NOT EXISTS audio_language_id BIGINT,ADD COLUMN IF NOT EXISTS subtitle_language_id BIGINT,
 ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(),ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
 CREATE TABLE release_sources(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT,source_type TEXT,type TEXT);
 CREATE TABLE stream_types(id BIGINT PRIMARY KEY,name TEXT);INSERT INTO stream_types VALUES(1,'episode');
 INSERT INTO stream_sources(provider_type,external_id,url,metadata) VALUES('jellyfin','item-a','https://old.invalid',
 '{"jellyfin_source":{"version":1,"media_source_id":"source-a","source_path":"/data/anime/FixtureFallback/a.mkv","streams_complete":true,"selected_audio_index":null,"audio_tracks":[],"subtitle_tracks":[]}}');
 INSERT INTO release_streams(variant_id,stream_source_id)SELECT 3301,id FROM stream_sources WHERE external_id='item-a';
 UPDATE release_variants SET filename='a.mkv',container='matroska',duration_seconds=1200 WHERE id=3301;
 `)
	require.NoError(t, err)
	testsupport.ApplySQLFile(t, pool, filepath.Join("..", "..", "..", "database", "migrations", "0166_jellyfin_source_identity.up.sql"))
	return pool
}
func hydrationState(t *testing.T, pool *pgxpool.Pool) string {
	t.Helper()
	var state string
	require.NoError(t, pool.QueryRow(context.Background(), `SELECT jsonb_build_array(
 (SELECT jsonb_agg(to_jsonb(x)) FROM release_versions x),
 (SELECT jsonb_agg(to_jsonb(x)) FROM release_variants x),
 (SELECT jsonb_agg(to_jsonb(x)) FROM release_streams x),
 (SELECT jsonb_agg(to_jsonb(x)) FROM stream_sources x))::text`).Scan(&state))
	return state
}
func hydrationPatch(h *FansubHandler, body string, admin bool) *httptest.ResponseRecorder {
	gin.SetMode(gin.TestMode)
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = httptest.NewRequest("PATCH", "/episode-versions/3301", strings.NewReader(body))
	c.Request.Header.Set("Content-Type", "application/json")
	c.Params = gin.Params{{Key: "versionId", Value: "3301"}}
	identity := evecFixturePlatformAdminIdentity()
	identity.IsPlatformAdmin = admin
	c.Set("auth_identity", identity)
	h.UpdateEpisodeVersion(c)
	return w
}
func TestEpisodeVersionSourceHydrationEndpoints(t *testing.T) {
	for _, scenario := range []string{"metadata only", "same binding", "valid relink", "missing source", "incomplete B", "wrong series", "outside item", "outside source", "upstream error", "not configured", "contributor"} {
		t.Run(scenario, func(t *testing.T) {
			pool := openVersionHydrationFixture(t)
			requests := 0
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				requests++
				require.Equal(t, "/Items", r.URL.Path)
				require.Equal(t, "item-b", r.URL.Query().Get("Ids"))
				require.Empty(t, r.URL.Query().Get("api_key"))
				require.Contains(t, r.Header.Get("Authorization"), "MediaBrowser")
				if scenario == "upstream error" {
					w.WriteHeader(502)
					return
				}
				series, itemPath, sourcePath := "series-401", "/data/anime/FixtureFallback/b.webm", "/data/anime/FixtureFallback/b.webm"
				if scenario == "wrong series" {
					series = "foreign"
				}
				if scenario == "outside item" {
					itemPath = "/other/b.webm"
				}
				if scenario == "outside source" {
					sourcePath = "/other/b.webm"
				}
				source := map[string]any{"Id": "source-b", "Path": sourcePath, "Container": "webm", "MediaStreams": []any{map[string]any{"Index": 0, "Type": "Video", "Codec": "vp9", "Width": 1280, "Height": 720}}}
				if scenario == "incomplete B" {
					delete(source, "MediaStreams")
				}
				json.NewEncoder(w).Encode(map[string]any{"Items": []any{map[string]any{"Id": "item-b", "Type": "Episode", "SeriesId": series, "Path": itemPath, "MediaSources": []any{source}}}, "TotalRecordCount": 1})
			}))
			defer server.Close()
			h := NewFansubHandler(repository.NewFansubRepository(pool), repository.NewEpisodeVersionRepository(pool), nil, "admin", FansubProxyConfig{JellyfinBaseURL: server.URL, JellyfinAPIKey: "fixture-token"})
			if scenario == "not configured" {
				h.jellyfinBaseURL = ""
			}
			body := `{"title":"My title","media_provider":"jellyfin","media_item_id":"item-b","media_source_id":"source-b","stream_url":"https://attacker.invalid","JellyfinSource":{"media_source_id":"forged"},"Container":"forged"}`
			if scenario == "same binding" {
				body = `{"title":"Same binding","media_provider":"jellyfin","media_item_id":"item-a","media_source_id":"source-a","stream_url":"https://old.invalid"}`
			}
			if scenario == "metadata only" {
				body = `{"title":"Only metadata","video_quality":"480p"}`
			}
			if scenario == "missing source" {
				body = strings.ReplaceAll(body, `"source-b"`, `"missing"`)
			}
			before := hydrationState(t, pool)
			result := hydrationPatch(h, body, scenario != "contributor")
			expected := 409
			switch scenario {
			case "metadata only", "same binding", "valid relink":
				expected = 200
			case "upstream error":
				expected = 502
			case "not configured":
				expected = 503
			case "contributor":
				expected = 403
			}
			require.Equal(t, expected, result.Code, result.Body.String())
			if expected != 200 {
				require.Equal(t, before, hydrationState(t, pool))
			}
			if scenario == "metadata only" || scenario == "same binding" || scenario == "contributor" || scenario == "not configured" {
				require.Zero(t, requests)
			} else {
				require.Equal(t, 1, requests)
			}
			if scenario == "valid relink" {
				var stored struct {
					Data models.EpisodeVersion `json:"data"`
				}
				require.NoError(t, json.Unmarshal(result.Body.Bytes(), &stored))
				require.Equal(t, "item-b", stored.Data.MediaItemID)
				require.Equal(t, hydrationText("source-b"), stored.Data.MediaSourceID)
				require.Equal(t, hydrationText("My title"), stored.Data.Title)
				require.NotContains(t, *stored.Data.StreamURL, "attacker")
				var filename, container string
				require.NoError(t, pool.QueryRow(context.Background(), "SELECT filename,container FROM release_variants WHERE id=3301").Scan(&filename, &container))
				require.Equal(t, "b.webm", filename)
				require.Equal(t, "webm", container)
			}
			t.Logf("%s: Jellyfin requests=%d; status=%d", scenario, requests, result.Code)
		})
	}
}
func TestEpisodeVersionSourceHydrationCreate(t *testing.T) {
	pool := openVersionHydrationFixture(t)
	_, err := pool.Exec(context.Background(), `ALTER TABLE fansub_releases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 4000);
 ALTER TABLE release_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 5000);
 ALTER TABLE release_variants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 6000);
 ALTER TABLE release_variant_episodes ADD PRIMARY KEY(release_variant_id,episode_id);
 CREATE TABLE app_user_global_roles(app_user_id BIGINT,role TEXT);INSERT INTO app_user_global_roles VALUES(4001,'platform_admin');`)
	require.NoError(t, err)
	requests := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests++
		json.NewEncoder(w).Encode(map[string]any{"Items": []any{map[string]any{"Id": "item-b", "Type": "Episode", "SeriesId": "series-401", "Path": "/data/anime/FixtureFallback/b.mkv", "MediaSources": []any{map[string]any{"Id": "source-b", "Path": "/data/anime/FixtureFallback/b.mkv", "Container": "matroska", "MediaStreams": []any{}}}}}})
	}))
	defer server.Close()
	h := NewFansubHandler(repository.NewFansubRepository(pool), repository.NewEpisodeVersionRepository(pool), nil, "admin", FansubProxyConfig{JellyfinBaseURL: server.URL, JellyfinAPIKey: "fixture-token"})
	h.authzRepo = repository.NewAuthzRepository(pool)
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = httptest.NewRequest("POST", "/anime/301/episodes/1/versions", strings.NewReader(`{"title":"Human title","media_provider":"Jellyfin","media_item_id":"item-b","media_source_id":"source-b","stream_url":"https://attacker.invalid","FileName":"forged.mkv"}`))
	c.Request.Header.Set("Content-Type", "application/json")
	c.Params = gin.Params{{Key: "id", Value: "301"}, {Key: "episodeNumber", Value: "1"}}
	c.Set("auth_identity", evecFixturePlatformAdminIdentity())
	h.CreateEpisodeVersion(c)
	require.Equal(t, 201, w.Code, w.Body.String())
	require.Equal(t, 1, requests)
	var item struct {
		Data models.EpisodeVersion `json:"data"`
	}
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &item))
	require.Equal(t, hydrationText("source-b"), item.Data.MediaSourceID)
	require.Equal(t, hydrationText("Human title"), item.Data.Title)
	var filename string
	require.NoError(t, pool.QueryRow(context.Background(), "SELECT filename FROM release_variants WHERE id=$1", item.Data.VariantID).Scan(&filename))
	require.Equal(t, "b.mkv", filename)
}

// The scan must use the same selected source as the mutation boundary, without
// suppressing alternate physical sources or creating per-source requests.
func TestEpisodeVersionSourceHydrationFolderScan(t *testing.T) {
	for _, scenario := range []string{"own source", "reverse sources", "complete empty", "same source incomplete", "new source incomplete", "ambiguous", "outside source", "wrong series", "outside item"} {
		t.Run(scenario, func(t *testing.T) {
			pool := openVersionHydrationFixture(t)
			root := "/data/anime/FixtureFallback"
			own := map[string]any{"Id": "source-a", "Path": root + "/a.mkv", "MediaStreams": []any{map[string]any{"Index": 0, "Type": "Video", "Height": 720}}}
			alternate := map[string]any{"Id": "alternate", "Path": root + "/alternate.mp4", "MediaStreams": []any{map[string]any{"Index": 0, "Type": "Video", "Height": 2160}}}
			next := map[string]any{"Id": "source-b", "Path": root + "/b.webm", "MediaStreams": []any{map[string]any{"Index": 0, "Type": "Video", "Height": 1080}}}
			sources := []any{alternate, own}
			itemPath, series := root+"/b.webm", "series-401"
			switch scenario {
			case "reverse sources":
				sources = []any{own, alternate}
			case "complete empty":
				own["MediaStreams"] = []any{}
			case "same source incomplete":
				delete(own, "MediaStreams")
			case "new source incomplete":
				delete(next, "MediaStreams")
			case "outside source":
				next["Path"] = "/private/foreign/b.webm"
			case "wrong series":
				series = "foreign"
			case "outside item":
				itemPath = "/private/foreign/b.webm"
			}
			nextAlternate := map[string]any{"Id": "alternate-b", "Path": root + "/alternate-b.mp4", "MediaStreams": []any{}}
			nextSources := []any{next, nextAlternate}
			if scenario == "outside source" {
				nextSources = []any{next}
			}
			if scenario == "ambiguous" {
				itemPath = root + "/missing.webm"
			}
			requests := 0
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				requests++
				require.Empty(t, r.URL.Query().Get("api_key"))
				require.Contains(t, r.Header.Get("Authorization"), "MediaBrowser")
				if r.URL.Path == "/Items" {
					require.Equal(t, "series-401", r.URL.Query().Get("Ids"))
					json.NewEncoder(w).Encode(map[string]any{"Items": []any{map[string]any{"Id": "series-401", "Path": root}}})
					return
				}
				require.Equal(t, "/Shows/series-401/Episodes", r.URL.Path)
				require.Contains(t, r.URL.Query().Get("Fields"), "MediaSources")
				json.NewEncoder(w).Encode(map[string]any{"TotalRecordCount": 2, "Items": []any{
					map[string]any{"Id": "item-b", "Type": "Episode", "SeriesId": series, "Path": itemPath, "IndexNumber": 2, "MediaSources": nextSources},
					map[string]any{"Id": "item-a", "Type": "Episode", "SeriesId": "series-401", "Path": root + "/alternate.mp4", "IndexNumber": 1, "MediaSources": sources, "MediaStreams": []any{map[string]any{"Index": 0, "Type": "Video", "Height": 480}}},
				}})
			}))
			defer server.Close()
			h := evecFixtureHandler(pool, server.URL, "fixture-key")
			before := hydrationState(t, pool)
			files, status, err := h.scanEpisodeVersionFolder(context.Background(), 3301)
			require.Equal(t, 2, requests, "one context lookup plus one collection request, no per-item hydration")
			require.Equal(t, before, hydrationState(t, pool), "folder scan is read-only")
			switch scenario {
			case "new source incomplete", "wrong series":
				require.Error(t, err)
				require.Equal(t, 409, status)
				require.NotContains(t, err.Error(), "/private")
				return
			}
			require.NoError(t, err)
			expected := 4
			if scenario == "outside item" || scenario == "outside source" {
				expected = 2
			}
			require.Len(t, files.Files, expected)
			a := files.Files[0]
			require.Equal(t, "item-a", a.MediaItemID)
			require.Equal(t, "source-a", derefString(a.MediaSourceID))
			require.Equal(t, "a.mkv", a.FileName)
			require.Equal(t, root+"/a.mkv", a.Path)
			require.Equal(t, "a", derefString(a.ReleaseName))
			if scenario == "complete empty" || scenario == "same source incomplete" {
				require.Nil(t, a.VideoQuality)
			} else {
				require.Equal(t, "720p", derefString(a.VideoQuality))
			}
			require.Nil(t, a.FileSizeBytes)
			require.Nil(t, a.LastModified)
			if expected == 4 {
				b := files.Files[3]
				require.Equal(t, "item-b", b.MediaItemID)
				require.Equal(t, "source-b", derefString(b.MediaSourceID))
				require.Equal(t, "b.webm", b.FileName)
				require.Equal(t, "1080p", derefString(b.VideoQuality))
			}
		})
	}
}
