package handlers

import (
 "context"
 "encoding/json"
 "fmt"
 "net/http"
 "net/http/httptest"
 "strings"
 "testing"

 "github.com/gin-gonic/gin"
 "github.com/jackc/pgx/v5/pgxpool"
 "github.com/stretchr/testify/require"
 "team4s.v3/backend/internal/models"
 "team4s.v3/backend/internal/repository"
)

func TestReleaseMetadataOnlyRejectsSourceSelector(t *testing.T) {
 var input models.EpisodeVersionPatchInput
 require.NoError(t,json.Unmarshal([]byte(`{"title":"A","media_source_id":"source-b"}`),&input))
 require.False(t,isReleaseMetadataOnlyPatch(input))
 valid,message:=validateEpisodeVersionPatchRequest(models.EpisodeVersionPatchInput{MediaSourceID:models.OptionalString{Set:true,Value:hydrationText("source-b")}})
 require.Empty(t,message);require.True(t,valid.MediaSourceID.Set)
 for _,source:=range []*string{nil,hydrationText(""),hydrationText("x,y")} {
  _,message=validateEpisodeVersionPatchRequest(models.EpisodeVersionPatchInput{MediaSourceID:models.OptionalString{Set:true,Value:source}})
  require.NotEmpty(t,message)
 }
}
func hydrationText(s string)*string{return &s}
func openVersionHydrationFixture(t *testing.T)*pgxpool.Pool {
 t.Helper();pool:=openEVECFixture(t)
 _,err:=pool.Exec(context.Background(),`
 ALTER TABLE fansub_releases ADD COLUMN source_id BIGINT,ADD COLUMN source BIGINT,ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(),ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
 ALTER TABLE release_versions ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(),ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
 ALTER TABLE release_variants ADD COLUMN filename TEXT,ADD COLUMN container TEXT,ADD COLUMN video_codec TEXT,ADD COLUMN audio_codec TEXT;
 ALTER TABLE stream_sources ADD COLUMN metadata JSONB NOT NULL DEFAULT '{}',ADD CONSTRAINT fixture_source_identity UNIQUE(provider_type,external_id);
 ALTER TABLE stream_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
 ALTER TABLE release_streams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
 ALTER TABLE release_streams ADD COLUMN stream_type_id BIGINT DEFAULT 1,ADD COLUMN audio_language_id BIGINT,ADD COLUMN subtitle_language_id BIGINT,
 ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(),ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
 CREATE TABLE release_sources(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT,source_type TEXT,type TEXT);
 CREATE TABLE stream_types(id BIGINT PRIMARY KEY,name TEXT);INSERT INTO stream_types VALUES(1,'episode');
 INSERT INTO stream_sources(provider_type,external_id,url,metadata) VALUES('jellyfin','item-a','https://old.invalid',
 '{"jellyfin_source":{"version":1,"media_source_id":"source-a","source_path":"/data/anime/FixtureFallback/a.mkv","streams_complete":true,"selected_audio_index":null,"audio_tracks":[],"subtitle_tracks":[]}}');
 INSERT INTO release_streams(variant_id,stream_source_id)SELECT 3301,id FROM stream_sources WHERE external_id='item-a';
 UPDATE release_variants SET filename='a.mkv',container='matroska',duration_seconds=1200 WHERE id=3301;
 `);require.NoError(t,err);return pool
}
func hydrationState(t *testing.T,pool *pgxpool.Pool)string {
 t.Helper();var state string
 require.NoError(t,pool.QueryRow(context.Background(),`SELECT jsonb_build_array(
 (SELECT jsonb_agg(to_jsonb(x)) FROM release_versions x),
 (SELECT jsonb_agg(to_jsonb(x)) FROM release_variants x),
 (SELECT jsonb_agg(to_jsonb(x)) FROM release_streams x),
 (SELECT jsonb_agg(to_jsonb(x)) FROM stream_sources x))::text`).Scan(&state));return state
}
func hydrationPatch(h *FansubHandler,body string,admin bool)*httptest.ResponseRecorder {
 gin.SetMode(gin.TestMode);w:=httptest.NewRecorder();c,_:=gin.CreateTestContext(w)
 c.Request=httptest.NewRequest("PATCH","/episode-versions/3301",strings.NewReader(body));c.Request.Header.Set("Content-Type","application/json")
 c.Params=gin.Params{{Key:"versionId",Value:"3301"}}
 identity:=evecFixturePlatformAdminIdentity();identity.IsPlatformAdmin=admin;c.Set("auth_identity",identity)
 h.UpdateEpisodeVersion(c);return w
}
func TestEpisodeVersionSourceHydrationEndpoints(t *testing.T) {
 for _,scenario:=range []string{"metadata only","valid relink","missing source","incomplete B","wrong series","outside item","outside source","upstream error","not configured","contributor"} {t.Run(scenario,func(t *testing.T){
  pool:=openVersionHydrationFixture(t);requests:=0
  server:=httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){
   requests++;require.Equal(t,"/Items",r.URL.Path);require.Equal(t,"item-b",r.URL.Query().Get("Ids"))
   require.Empty(t,r.URL.Query().Get("api_key"));require.Contains(t,r.Header.Get("Authorization"),"MediaBrowser")
   if scenario=="upstream error"{w.WriteHeader(502);return}
   series,itemPath,sourcePath:="series-401","/data/anime/FixtureFallback/b.webm","/data/anime/FixtureFallback/b.webm"
   if scenario=="wrong series"{series="foreign"};if scenario=="outside item"{itemPath="/other/b.webm"};if scenario=="outside source"{sourcePath="/other/b.webm"}
   source:=map[string]any{"Id":"source-b","Path":sourcePath,"Container":"webm","MediaStreams":[]any{map[string]any{"Index":0,"Type":"Video","Codec":"vp9","Width":1280,"Height":720}}}
   if scenario=="incomplete B"{delete(source,"MediaStreams")}
   json.NewEncoder(w).Encode(map[string]any{"Items":[]any{map[string]any{"Id":"item-b","Type":"Episode","SeriesId":series,"Path":itemPath,"MediaSources":[]any{source}}},"TotalRecordCount":1})
  }));defer server.Close()
  h:=NewFansubHandler(repository.NewFansubRepository(pool),repository.NewEpisodeVersionRepository(pool),nil,"admin",FansubProxyConfig{JellyfinBaseURL:server.URL,JellyfinAPIKey:"fixture-token"})
  if scenario=="not configured"{h.jellyfinBaseURL=""}
  body:=`{"title":"My title","media_provider":"jellyfin","media_item_id":"item-b","media_source_id":"source-b","stream_url":"https://attacker.invalid","JellyfinSource":{"media_source_id":"forged"},"Container":"forged"}`
  if scenario=="metadata only"{body=`{"title":"Only metadata","video_quality":"480p"}`}
  if scenario=="missing source"{body=strings.ReplaceAll(body,`"source-b"`,`"missing"`)}
  before:=hydrationState(t,pool);result:=hydrationPatch(h,body,scenario!="contributor")
  expected:=409
  switch scenario {case "metadata only","valid relink":expected=200;case "upstream error":expected=502;case "not configured":expected=503;case "contributor":expected=403}
  require.Equal(t,expected,result.Code,result.Body.String())
  if expected!=200 {require.Equal(t,before,hydrationState(t,pool))}
  if scenario=="metadata only"||scenario=="contributor"||scenario=="not configured"{require.Zero(t,requests)}else{require.Equal(t,1,requests)}
  if scenario=="valid relink"{
   var stored struct{Data models.EpisodeVersion `json:"data"`};require.NoError(t,json.Unmarshal(result.Body.Bytes(),&stored))
   require.Equal(t,"item-b",stored.Data.MediaItemID);require.Equal(t,hydrationText("source-b"),stored.Data.MediaSourceID)
   require.Equal(t,hydrationText("My title"),stored.Data.Title);require.NotContains(t,*stored.Data.StreamURL,"attacker")
   var filename,container string;require.NoError(t,pool.QueryRow(context.Background(),"SELECT filename,container FROM release_variants WHERE id=3301").Scan(&filename,&container))
   require.Equal(t,"b.webm",filename);require.Equal(t,"webm",container)
  }
  t.Logf("%s: Jellyfin requests=%d; status=%d",scenario,requests,result.Code)
 })}
}
var _ = fmt.Sprint
