package main

import (
	"team4s.v3/backend/internal/handlers"

	"github.com/gin-gonic/gin"
)

type adminRouteHandlers struct {
	adminContentHandler *handlers.AdminContentHandler
	animeHandler        *handlers.AnimeHandler
	fansubHandler       *handlers.FansubHandler
	mediaUploadHandler  *handlers.MediaUploadHandler
	appAuthHandler      *handlers.AppAuthHandler
}

func registerAdminRoutes(v1 *gin.RouterGroup, auth gin.HandlerFunc, deps adminRouteHandlers) {
	v1.GET("/admin/anime", auth, deps.animeHandler.List)
	v1.GET("/admin/anime/:id", auth, deps.animeHandler.GetByID)
	v1.POST("/admin/anime", auth, deps.adminContentHandler.CreateAnime)
	v1.PATCH("/admin/anime/:id", auth, deps.adminContentHandler.UpdateAnime)
	v1.DELETE("/admin/anime/:id", auth, deps.adminContentHandler.DeleteAnime)
	v1.GET("/admin/anime/:id/relations", auth, deps.adminContentHandler.ListAnimeRelations)
	v1.GET("/admin/anime/:id/relation-targets", auth, deps.adminContentHandler.SearchAnimeRelationTargets)
	v1.POST("/admin/anime/:id/relations", auth, deps.adminContentHandler.CreateAnimeRelation)
	v1.PATCH("/admin/anime/:id/relations/:targetAnimeId", auth, deps.adminContentHandler.UpdateAnimeRelation)
	v1.DELETE("/admin/anime/:id/relations/:targetAnimeId", auth, deps.adminContentHandler.DeleteAnimeRelation)
	v1.PUT("/admin/anime/:id/assets/cover", auth, deps.adminContentHandler.AssignAnimeCoverAsset)
	v1.DELETE("/admin/anime/:id/assets/cover", auth, deps.adminContentHandler.DeleteAnimeCoverAsset)
	v1.PUT("/admin/anime/:id/assets/banner", auth, deps.adminContentHandler.AssignAnimeBannerAsset)
	v1.DELETE("/admin/anime/:id/assets/banner", auth, deps.adminContentHandler.DeleteAnimeBannerAsset)
	v1.PUT("/admin/anime/:id/assets/logo", auth, deps.adminContentHandler.AssignAnimeLogoAsset)
	v1.DELETE("/admin/anime/:id/assets/logo", auth, deps.adminContentHandler.DeleteAnimeLogoAsset)
	v1.PUT("/admin/anime/:id/assets/background_video", auth, deps.adminContentHandler.AssignAnimeBackgroundVideoAsset)
	v1.DELETE("/admin/anime/:id/assets/background_video", auth, deps.adminContentHandler.DeleteAnimeBackgroundVideoAsset)
	v1.POST("/admin/anime/:id/assets/background_videos", auth, deps.adminContentHandler.AddAnimeBackgroundVideoAsset)
	v1.POST("/admin/anime/:id/assets/backgrounds", auth, deps.adminContentHandler.AddAnimeBackgroundAsset)
	v1.DELETE("/admin/anime/:id/assets/backgrounds/:backgroundId", auth, deps.adminContentHandler.DeleteAnimeBackgroundAsset)
	v1.GET("/admin/anime/assets/search", auth, deps.adminContentHandler.SearchAnimeCreateAssetCandidates)
	v1.POST("/admin/anime/enrichment/anisearch", auth, deps.adminContentHandler.LoadAnimeCreateAniSearchEnrichment)
	v1.GET("/admin/anime/enrichment/anisearch/search", auth, deps.adminContentHandler.SearchAnimeCreateAniSearchCandidates)
	v1.POST("/admin/anime/:id/enrichment/anisearch", auth, deps.adminContentHandler.LoadAnimeAniSearchEnrichment)
	v1.GET("/admin/anime/:id/jellyfin/context", auth, deps.adminContentHandler.GetAnimeJellyfinContext)
	v1.POST("/admin/anime/:id/jellyfin/metadata/preview", auth, deps.adminContentHandler.PreviewAnimeMetadataFromJellyfin)
	v1.POST("/admin/anime/:id/jellyfin/metadata/apply", auth, deps.adminContentHandler.ApplyAnimeMetadataFromJellyfin)
	v1.POST("/admin/anime/:id/jellyfin/sync", auth, deps.adminContentHandler.SyncAnimeFromJellyfin)
	v1.POST("/admin/anime/:id/episodes/:episodeId/sync", auth, deps.adminContentHandler.SyncEpisodeFromJellyfin)
	v1.GET("/admin/anime/:id/episode-import/context", auth, deps.adminContentHandler.GetEpisodeImportContext)
	v1.POST("/admin/anime/:id/episode-import/preview", auth, deps.adminContentHandler.PreviewEpisodeImport)
	v1.POST("/admin/anime/:id/episode-import/apply", auth, deps.adminContentHandler.ApplyEpisodeImport)
	v1.GET("/admin/jellyfin/series", auth, deps.adminContentHandler.SearchJellyfinSeries)
	v1.POST("/admin/jellyfin/intake/preview", auth, deps.adminContentHandler.PreviewAnimeIntakeFromJellyfin)
	v1.POST("/admin/anime/:id/jellyfin/preview", auth, deps.adminContentHandler.PreviewAnimeFromJellyfin)
	v1.GET("/admin/episode-versions/:versionId/editor-context", auth, deps.adminContentHandler.GetEpisodeVersionEditorContext)
	v1.POST("/admin/episode-versions/:versionId/folder-scan", auth, deps.adminContentHandler.ScanEpisodeVersionFolder)
	v1.POST("/admin/episodes", auth, deps.adminContentHandler.CreateEpisode)
	v1.GET("/admin/genres", auth, deps.adminContentHandler.ListGenreTokens)
	v1.GET("/admin/tags", auth, deps.adminContentHandler.ListTagTokens)
	v1.PATCH("/admin/episodes/:id", auth, deps.adminContentHandler.UpdateEpisode)
	v1.DELETE("/admin/episodes/:id", auth, deps.adminContentHandler.DeleteEpisode)
	v1.POST("/admin/fansubs/:id/media", auth, deps.fansubHandler.UploadFansubMedia)
	v1.DELETE("/admin/fansubs/:id/media/:kind", auth, deps.fansubHandler.DeleteFansubMedia)
	v1.POST("/fansubs", auth, deps.fansubHandler.CreateFansub)
	v1.PATCH("/fansubs/:id", auth, deps.fansubHandler.UpdateFansub)
	v1.DELETE("/fansubs/:id", auth, deps.fansubHandler.DeleteFansub)
	v1.GET("/admin/fansubs/:id/links", auth, deps.fansubHandler.ListFansubLinks)
	v1.POST("/admin/fansubs/:id/links", auth, deps.fansubHandler.CreateFansubLink)
	v1.PATCH("/admin/fansubs/:id/links/:linkId", auth, deps.fansubHandler.UpdateFansubLink)
	v1.DELETE("/admin/fansubs/:id/links/:linkId", auth, deps.fansubHandler.DeleteFansubLink)
	v1.POST("/fansubs/:id/aliases", auth, deps.fansubHandler.CreateFansubAlias)
	v1.DELETE("/fansubs/:id/aliases/:aliasId", auth, deps.fansubHandler.DeleteFansubAlias)
	v1.POST("/fansubs/:id/members", auth, deps.fansubHandler.CreateFansubMember)
	v1.PATCH("/fansubs/:id/members/:memberId", auth, deps.fansubHandler.UpdateFansubMember)
	v1.DELETE("/fansubs/:id/members/:memberId", auth, deps.fansubHandler.DeleteFansubMember)
	v1.POST("/anime/:id/fansubs/:fansubId", auth, deps.fansubHandler.AttachAnimeFansub)
	v1.DELETE("/anime/:id/fansubs/:fansubId", auth, deps.fansubHandler.DetachAnimeFansub)
	v1.POST("/anime/:id/episodes/:episodeNumber/versions", auth, deps.fansubHandler.CreateEpisodeVersion)
	v1.PATCH("/episode-versions/:versionId", auth, deps.fansubHandler.UpdateEpisodeVersion)
	v1.DELETE("/episode-versions/:versionId", auth, deps.fansubHandler.DeleteEpisodeVersion)
	v1.POST("/admin/fansubs/merge", auth, deps.fansubHandler.MergeFansubs)
	v1.POST("/admin/fansubs/merge/preview", auth, deps.fansubHandler.MergeFansubsPreview)
	v1.POST("/admin/upload", auth, deps.mediaUploadHandler.Upload)
	v1.DELETE("/admin/media/:id", auth, deps.mediaUploadHandler.Delete)
	v1.GET("/admin/theme-types", auth, deps.adminContentHandler.ListThemeTypes)
	v1.GET("/admin/anime/:id/themes", auth, deps.adminContentHandler.ListAnimeThemes)
	v1.POST("/admin/anime/:id/themes", auth, deps.adminContentHandler.CreateAnimeTheme)
	v1.PATCH("/admin/anime/:id/themes/:themeId", auth, deps.adminContentHandler.UpdateAnimeTheme)
	v1.DELETE("/admin/anime/:id/themes/:themeId", auth, deps.adminContentHandler.DeleteAnimeTheme)
	v1.GET("/admin/anime/:id/segments", auth, deps.adminContentHandler.ListAnimeSegments)
	v1.GET("/admin/anime/:id/segments/library-candidates", auth, deps.adminContentHandler.ListSegmentLibraryCandidates)
	v1.GET("/admin/anime/:id/segments/suggestions", auth, deps.adminContentHandler.GetAnimeSegmentSuggestions)
	v1.POST("/admin/anime/:id/segments", auth, deps.adminContentHandler.CreateAnimeSegment)
	v1.PATCH("/admin/anime/:id/segments/:segmentId", auth, deps.adminContentHandler.UpdateAnimeSegment)
	v1.DELETE("/admin/anime/:id/segments/:segmentId", auth, deps.adminContentHandler.DeleteAnimeSegment)
	v1.POST("/admin/anime/:id/segments/:segmentId/reuse", auth, deps.adminContentHandler.AttachSegmentLibraryAsset)
	v1.POST("/admin/anime/:id/segments/:segmentId/asset", auth, deps.adminContentHandler.UploadSegmentAsset)
	v1.DELETE("/admin/anime/:id/segments/:segmentId/asset", auth, deps.adminContentHandler.DeleteSegmentAsset)
	v1.GET("/admin/fansubs/:id/anime", auth, deps.adminContentHandler.ListFansubAnime)
	v1.GET("/admin/fansubs/:id/anime/:animeId/releases", auth, deps.adminContentHandler.ListFansubAnimeReleases)
	v1.GET("/admin/fansubs/:id/anime/:animeId/releases/canonical", auth, deps.adminContentHandler.GetCanonicalFansubAnimeReleaseSummary)
	v1.GET("/admin/fansubs/:id/anime/:animeId/theme-assets", auth, deps.adminContentHandler.ListFansubAnimeThemeAssets)
	v1.POST("/admin/fansubs/:id/anime/:animeId/theme-assets", auth, deps.adminContentHandler.UploadReleaseThemeAsset)
	v1.GET("/admin/releases/:releaseId", auth, deps.adminContentHandler.GetAdminRelease)
	v1.GET("/admin/releases/:releaseId/theme-assets", auth, deps.adminContentHandler.ListReleaseThemeAssets)
	v1.POST("/admin/releases/:releaseId/theme-assets", auth, deps.adminContentHandler.UploadReleaseThemeAssetForRelease)
	v1.DELETE("/admin/releases/:releaseId/theme-assets/:themeId/:mediaId", auth, deps.adminContentHandler.DeleteReleaseThemeAsset)
	// Release-Version Media routes (Phase 35)
	// NOTE: /reorder must be registered BEFORE /:relationId so Gin matches the literal segment first.
	v1.POST("/admin/release-versions/:versionId/media", auth, deps.adminContentHandler.UploadReleaseVersionMedia)
	v1.GET("/admin/release-versions/:versionId/capabilities", auth, deps.adminContentHandler.GetReleaseVersionCapabilities)
	v1.GET("/admin/release-versions/:versionId/media", auth, deps.adminContentHandler.ListReleaseVersionMedia)
	v1.POST("/admin/release-versions/:versionId/media/reorder", auth, deps.adminContentHandler.ReorderReleaseVersionMedia)
	v1.PATCH("/admin/release-versions/:versionId/media/:relationId", auth, deps.adminContentHandler.PatchReleaseVersionMedia)
	v1.DELETE("/admin/release-versions/:versionId/media/:relationId", auth, deps.adminContentHandler.DeleteReleaseVersionMedia)
	// Release-Version-Notes routes (Phase 40)
	v1.GET("/admin/release-versions/:versionId/notes", auth, deps.adminContentHandler.ListReleaseVersionNotes)
	v1.POST("/admin/release-versions/:versionId/notes", auth, deps.adminContentHandler.BulkUpsertReleaseVersionNotes)
	v1.DELETE("/admin/release-versions/:versionId/notes/:noteId", auth, deps.adminContentHandler.DeleteReleaseVersionNote)
	v1.GET("/admin/release-versions/:versionId/member-roles", auth, deps.adminContentHandler.GetMemberRolesForVersion)
	v1.GET("/admin/users", auth, deps.appAuthHandler.ListAppUsers)
	v1.GET("/admin/fansubs/:id/capabilities", auth, deps.appAuthHandler.GetFansubGroupCapabilities)
	v1.GET("/admin/fansubs/:id/app-members", auth, deps.appAuthHandler.ListFansubGroupAppMembers)
	v1.GET("/admin/fansubs/:id/app-member-candidates", auth, deps.appAuthHandler.SearchFansubGroupAppMemberCandidates)
	v1.POST("/admin/fansubs/:id/app-members", auth, deps.appAuthHandler.CreateFansubGroupAppMember)
	v1.GET("/admin/fansubs/:id/invitations", auth, deps.appAuthHandler.ListFansubGroupInvitations)
	v1.POST("/admin/fansubs/:id/invitations", auth, deps.appAuthHandler.CreateFansubGroupInvitation)
	v1.POST("/admin/fansubs/:id/invitations/:invitationId/cancel", auth, deps.appAuthHandler.CancelFansubGroupInvitation)
	v1.PUT("/admin/fansubs/:id/app-members/:appUserId/roles", auth, deps.appAuthHandler.SetFansubGroupMemberRole)
	v1.PUT("/admin/fansubs/:id/app-members/:appUserId/status", auth, deps.appAuthHandler.UpdateFansubGroupMemberStatus)
	v1.PUT("/admin/fansubs/:id/app-members/:appUserId/roles/fansub-lead", auth, deps.appAuthHandler.SetFansubLead)
	// Fansub-Notes routes (Phase 40)
	v1.GET("/admin/fansubs/:id/notes", auth, deps.adminContentHandler.ListFansubGroupNotes)
	v1.POST("/admin/fansubs/:id/notes", auth, deps.adminContentHandler.CreateFansubGroupNote)
	v1.PATCH("/admin/fansubs/:id/notes/:noteId", auth, deps.adminContentHandler.UpdateFansubGroupNote)
	v1.DELETE("/admin/fansubs/:id/notes/:noteId", auth, deps.adminContentHandler.DeleteFansubGroupNote)
	v1.GET("/admin/fansubs/:id/member-stories/context", auth, deps.adminContentHandler.GetMemberGroupStoryContext)
	v1.GET("/admin/fansubs/:id/member-stories", auth, deps.adminContentHandler.ListMemberGroupStories)
	v1.POST("/admin/fansubs/:id/member-stories", auth, deps.adminContentHandler.CreateMemberGroupStory)
	v1.PATCH("/admin/fansubs/:id/member-stories/:storyId", auth, deps.adminContentHandler.UpdateMemberGroupStory)
	v1.DELETE("/admin/fansubs/:id/member-stories/:storyId", auth, deps.adminContentHandler.DeleteMemberGroupStory)
	v1.GET("/admin/fansubs/:id/anime/:animeId/notes", auth, deps.adminContentHandler.GetAnimeFansubProjectNote)
	v1.PUT("/admin/fansubs/:id/anime/:animeId/notes", auth, deps.adminContentHandler.UpsertAnimeFansubProjectNote)
	v1.DELETE("/admin/fansubs/:id/anime/:animeId/notes/:noteId", auth, deps.adminContentHandler.DeleteAnimeFansubProjectNote)
}
