// @vitest-environment jsdom
import { render, screen } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import type { FansubGroupCapabilities } from '@/types/fansub'
import { FansubBasicInfoTab } from './FansubBasicInfoTab'
vi.mock('@/components/admin/MediaUpload', () => ({ MediaUpload: ({ type, disabled }: { type: string; disabled?: boolean }) => <button disabled={disabled}>{type}</button> }))
const base: FansubGroupCapabilities = { can_edit_group:false, can_edit_group_general:false, can_edit_technical_links:false, can_edit_founding_history:false, can_update_group_links:false, can_manage_links:false, can_view_members:false, can_manage_members:false, can_manage_historical_members:false, can_manage_historical_roles:false, can_link_historical_members:false, can_edit_notes:false, can_view_invitations:false, can_create_invitation:false, can_cancel_invitation:false, can_view_releases:false, can_view_release_media:false, can_upload_release_media:false, can_edit_release_notes:false, can_view_group_media:false, can_upload_group_media:false, can_update_group_media:false, can_delete_own_group_media:false, can_delete_group_media:false, can_reorder_group_media:false }
function renderTab(overrides: Partial<FansubGroupCapabilities>, isPlatformAdmin = false) {
 const details = { form:{name:'Gruppe',slug:'gruppe',status:'active',groupType:'group',country:'Deutschland',websiteURL:'',discordURL:'',ircURL:'',foundedYear:'2004',dissolvedYear:''}, setForm:vi.fn(), aliases:[],aliasInput:'',setAliasInput:vi.fn(),aliasError:null,setAliasError:vi.fn(),setLinks:vi.fn(),setManualSlug:vi.fn(),saving:false,aliasBusy:false,logoMedia:null,setLogoMedia:vi.fn(),bannerMedia:null,setBannerMedia:vi.fn(),setInitialLogoMedia:vi.fn(),setInitialBannerMedia:vi.fn(),nameError:null,slugFormatError:null,foundedError:null,dissolvedError:null,dissolvedAfterFoundedError:null,technicalLinkErrors:{website:null,discord:null,irc:null},slugConflict:false,slugChecking:false,handleLogoMediaBusyChange:vi.fn(),handleBannerMediaBusyChange:vi.fn(),addAlias:vi.fn(),removeAlias:vi.fn() }
 render(<FansubBasicInfoTab styles={{}} details={details as never} fansubID={7} group={null} capabilities={{...base,...overrides}} isPlatformAdmin={isPlatformAdmin} hasAuthSession onToast={vi.fn()} communityLinksList={<div>Links</div>} />)
}
describe('FansubBasicInfoTab field capabilities', () => {
 it('enables only general fields for can_edit_group_general', () => { renderTab({can_edit_group_general:true}); expect(screen.getByLabelText(/Fansubgruppen-Name/)).not.toHaveProperty('disabled', true); expect(screen.getByLabelText('Land')).not.toHaveProperty('disabled', true); expect(screen.getByLabelText(/Status/)).toHaveProperty('disabled', true); expect(screen.getByLabelText('Gruppentyp')).toHaveProperty('disabled', true) })
 it('enables lifecycle fields on the broad path', () => { renderTab({can_edit_group:true}); expect(screen.getByLabelText(/Status/)).not.toHaveProperty('disabled', true); expect(screen.getByLabelText('Gruppentyp')).not.toHaveProperty('disabled', true) })
 it('keeps fields disabled without an exact right', () => { renderTab({}); expect(screen.getByLabelText(/Fansubgruppen-Name/)).toHaveProperty('disabled', true); expect(screen.getByLabelText('Land')).toHaveProperty('disabled', true); expect(screen.getByLabelText(/Status/)).toHaveProperty('disabled', true); expect(screen.getByLabelText('Gruppentyp')).toHaveProperty('disabled', true) })
 it('enables only technical URL fields for can_edit_technical_links', () => { renderTab({can_edit_technical_links:true}); expect(screen.getByLabelText('Website')).not.toHaveProperty('disabled', true); expect(screen.getByLabelText('Discord')).not.toHaveProperty('disabled', true); expect(screen.getByLabelText('IRC')).not.toHaveProperty('disabled', true); expect(screen.getByLabelText(/Fansubgruppen-Name/)).toHaveProperty('disabled', true); expect(screen.getByLabelText(/Status/)).toHaveProperty('disabled', true) })
 it('hides link creation for update-only actors', () => { renderTab({can_update_group_links:true}); expect(screen.queryByRole('button',{name:'Link hinzufügen'})).toHaveProperty('disabled', true); expect(screen.getByText('Links')).toBeTruthy() })
 it('hides Logo und Banner entirely for a co_leader-shaped capability set (can_update_group_media without can_edit_group)', () => { renderTab({can_edit_group:false, can_update_group_media:true}); expect(screen.queryByText('Logo und Banner')).toBeNull() })
 it('shows Logo und Banner for can_edit_group', () => { renderTab({can_edit_group:true}); expect(screen.getByText('Logo und Banner')).toBeTruthy(); expect(screen.getByRole('button',{name:'logo'})).toBeTruthy(); expect(screen.getByRole('button',{name:'banner'})).toBeTruthy() })
 it('shows Logo und Banner for isPlatformAdmin', () => { renderTab({}, true); expect(screen.getByText('Logo und Banner')).toBeTruthy() })
})
