package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"team4s.v3/backend/internal/testsupport"

	"github.com/disintegration/imaging"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/require"
)

// requireFFmpegBinary resolves an installed ffmpeg binary or fails the test immediately --
// this backfill is proven against REAL ffmpeg frame extraction, never a mocked extractor
// (established pattern, see segment_render_service_test.go).
func requireFFmpegBinary(t *testing.T) string {
	t.Helper()
	path, err := exec.LookPath("ffmpeg")
	if err != nil {
		t.Fatal("installed FFmpeg is required for backfill proof")
	}
	return path
}

// openBackfillTestFixture extends the shared Phase-117 fixture (already carries migration
// 0177 / theme_segments.auto_preview_media_asset_id, see testsupport.OpenPhase117Postgres)
// with the minimal media_assets/media_types/review_statuses/media_files schema slice that
// the REAL repository.MediaRepository (CreateMediaAsset/InsertMediaFile) needs -- identical
// shape to openSegmentPreviewAutoMediaFixture in
// internal/handlers/segment_render_worker_test.go, which proves the exact same write path
// from the render-worker side (Plan 172-04).
func openBackfillTestFixture(t *testing.T) *pgxpool.Pool {
	t.Helper()
	pool := testsupport.OpenPhase117Postgres(t)
	ctx := context.Background()
	_, err := pool.Exec(ctx, `
ALTER TABLE media_assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE media_assets
    ADD COLUMN media_type_id BIGINT,
    ADD COLUMN mime_type TEXT,
    ADD COLUMN format TEXT,
    ADD COLUMN visibility_id BIGINT REFERENCES visibilities(id),
    ADD COLUMN review_status_id BIGINT,
    ADD COLUMN created_at TIMESTAMPTZ;

CREATE TABLE media_types (id BIGINT PRIMARY KEY, name TEXT NOT NULL UNIQUE);
INSERT INTO media_types (id, name) VALUES (1, 'video'), (2, 'image');

CREATE TABLE review_statuses (id BIGINT PRIMARY KEY, code TEXT NOT NULL UNIQUE);
INSERT INTO review_statuses (id, code) VALUES (1, 'approved'), (2, 'in_review');

CREATE TABLE media_files (
    media_id BIGINT NOT NULL,
    variant TEXT NOT NULL,
    path TEXT NOT NULL,
    width INT NOT NULL DEFAULT 0,
    height INT NOT NULL DEFAULT 0,
    size BIGINT NOT NULL DEFAULT 0
);
`)
	require.NoError(t, err)
	return pool
}

// setupBackfillSegment creates the minimal anime/theme_type/theme/theme_segment chain a
// backfill candidate needs. Returns the new theme_segment's id.
func setupBackfillSegment(t *testing.T, pool *pgxpool.Pool, segmentID int64) int64 {
	t.Helper()
	ctx := context.Background()
	animeID := segmentID + 1000
	themeTypeID := segmentID + 2000
	themeID := segmentID + 3000

	_, err := pool.Exec(ctx, `INSERT INTO anime (id) VALUES ($1)`, animeID)
	require.NoError(t, err)
	_, err = pool.Exec(ctx, `INSERT INTO theme_types (id, name) VALUES ($1, 'OP1')`, themeTypeID)
	require.NoError(t, err)
	_, err = pool.Exec(ctx, `INSERT INTO themes (id, anime_id, theme_type_id) VALUES ($1, $2, $3)`, themeID, animeID, themeTypeID)
	require.NoError(t, err)
	_, err = pool.Exec(ctx, `INSERT INTO theme_segments (id, theme_id) VALUES ($1, $2)`, segmentID, themeID)
	require.NoError(t, err)
	return segmentID
}

// insertReadyRenderCache inserts a 'ready' theme_segment_render_cache row satisfying the real
// migration-0122 CHECK constraint (output_path/mime_type/duration_seconds/video_codec/
// audio_codec/completed_at all required once status='ready').
func insertReadyRenderCache(t *testing.T, pool *pgxpool.Pool, segmentID int64, cacheKey, outputPath string, durationSeconds int, completedAt time.Time) {
	t.Helper()
	_, err := pool.Exec(context.Background(), `
		INSERT INTO theme_segment_render_cache
			(theme_segment_id, cache_key, source_kind, source_fingerprint, render_profile,
			 status, output_path, mime_type, duration_seconds, video_codec, audio_codec, completed_at)
		VALUES ($1, $2, 'episode_version', $3, 'default',
			'ready', $4, 'video/mp4', $5, 'h264', 'aac', $6)
	`, segmentID, cacheKey, "fingerprint-"+cacheKey, outputPath, durationSeconds, completedAt)
	require.NoError(t, err)
}

// generateSolidColorFixtureVideo writes a short, single-solid-color synthetic video via
// ffmpeg's lavfi color source -- every frame in the clip has the same color, so a 35%-offset
// extraction is trivially verifiable regardless of ffmpeg's exact frame-seeking behavior at
// low framerates (see 172-04-SUMMARY.md's documented -ss/decode-seeking caveat).
func generateSolidColorFixtureVideo(t *testing.T, ffmpegBinary, outputPath, color string, durationSeconds int) {
	t.Helper()
	cmd := exec.Command(ffmpegBinary, "-y", "-f", "lavfi",
		"-i", fmt.Sprintf("color=c=%s:s=16x16:d=%d:r=1", color, durationSeconds),
		"-pix_fmt", "yuv420p", outputPath)
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generate %s fixture video: %v\n%s", color, err, output)
	}
}

// countMediaAssets returns the total row count in media_assets, used to prove idempotency
// (a second backfill run must not create any new rows for an already-processed segment).
func countMediaAssets(t *testing.T, pool *pgxpool.Pool) int {
	t.Helper()
	var count int
	require.NoError(t, pool.QueryRow(context.Background(), `SELECT COUNT(*) FROM media_assets`).Scan(&count))
	return count
}

func autoPreviewAssetID(t *testing.T, pool *pgxpool.Pool, segmentID int64) *int64 {
	t.Helper()
	var id *int64
	require.NoError(t, pool.QueryRow(context.Background(),
		`SELECT auto_preview_media_asset_id FROM theme_segments WHERE id = $1`, segmentID).Scan(&id))
	return id
}

// backfillTestImageStore ersetzt den globalen Anime-Upload-Pfad (StoreGeneratedAnimeImage,
// dort separat bewiesen): kopiert den extrahierten Frame in storageDir und legt die
// media_assets/media_files-Zeilen im Fixture-Schema an. animeIDs protokolliert die Aufrufe.
type backfillTestImageStore struct {
	pool       *pgxpool.Pool
	storageDir string
	animeIDs   []int64
}

func (s *backfillTestImageStore) StoreGeneratedAnimeImage(ctx context.Context, sourcePath string, animeID int64, assetType string) (int64, error) {
	s.animeIDs = append(s.animeIDs, animeID)
	data, err := os.ReadFile(sourcePath)
	if err != nil {
		return 0, err
	}
	dest := filepath.Join(s.storageDir, "anime", fmt.Sprint(animeID), assetType, fmt.Sprintf("frame-%d.jpg", len(s.animeIDs)))
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return 0, err
	}
	if err := os.WriteFile(dest, data, 0o644); err != nil {
		return 0, err
	}
	var id int64
	if err := s.pool.QueryRow(ctx, `
		INSERT INTO media_assets (media_type_id, file_path, mime_type, format, created_at)
		VALUES (2, $1, 'image/jpeg', 'image', NOW()) RETURNING id
	`, dest).Scan(&id); err != nil {
		return 0, err
	}
	_, err = s.pool.Exec(ctx, `INSERT INTO media_files (media_id, variant, path, size) VALUES ($1, 'original', $2, 0)`, id, dest)
	return id, err
}

func backfillTestConfig(pool *pgxpool.Pool, renderDir, storageDir, ffmpegBinary string) Config {
	return Config{
		SegmentRenderDir: renderDir,
		MediaStorageDir:  storageDir,
		FFmpegPath:       ffmpegBinary,
		DryRun:           false,
		ImageStore:       &backfillTestImageStore{pool: pool, storageDir: storageDir},
	}
}

// TestRunBackfill_PopulatesAutoPreviewForReadySegment proves D-13: a segment with exactly one
// ready render and no existing automatic preview gets a real auto_preview_media_asset_id,
// backed by a real media_assets/media_files row and a real extracted JPEG on disk.
func TestRunBackfill_PopulatesAutoPreviewForReadySegment(t *testing.T) {
	ffmpegBinary := requireFFmpegBinary(t)
	pool := openBackfillTestFixture(t)

	const segmentID = int64(7)
	setupBackfillSegment(t, pool, segmentID)

	renderDir := t.TempDir()
	outputRel := "segment-7.mp4"
	generateSolidColorFixtureVideo(t, ffmpegBinary, filepath.Join(renderDir, outputRel), "red", 4)
	insertReadyRenderCache(t, pool, segmentID, "cache-7", outputRel, 4, time.Now())

	storageDir := t.TempDir()
	cfg := backfillTestConfig(pool, renderDir, storageDir, ffmpegBinary)

	stats, err := runBackfill(context.Background(), pool, cfg)
	require.NoError(t, err)
	require.Equal(t, 1, stats.TotalCandidates)
	require.Equal(t, 1, stats.ProcessedOK)
	require.Equal(t, 0, stats.Failed)
	require.Equal(t, []int64{segmentID + 1000}, cfg.ImageStore.(*backfillTestImageStore).animeIDs, "frame must be stored for the segment's anime as segment_preview")

	assetID := autoPreviewAssetID(t, pool, segmentID)
	require.NotNil(t, assetID, "segment should now have an automatic preview asset")
	require.Greater(t, *assetID, int64(0))

	var filesCount int
	require.NoError(t, pool.QueryRow(context.Background(),
		`SELECT COUNT(*) FROM media_files WHERE media_id = $1 AND variant = 'original'`, *assetID).Scan(&filesCount))
	require.Equal(t, 1, filesCount, "exactly one media_files row for the new asset")

	var storedPath string
	require.NoError(t, pool.QueryRow(context.Background(),
		`SELECT path FROM media_files WHERE media_id = $1`, *assetID).Scan(&storedPath))
	if _, statErr := os.Stat(storedPath); statErr != nil {
		t.Fatalf("expected extracted preview file to exist on disk at %s: %v", storedPath, statErr)
	}
}

// TestRunBackfill_IdempotentOnSecondRun proves D-13's idempotency requirement: running the
// backfill twice against the same unchanged state must not create a second media_assets row
// or touch the segment's auto_preview_media_asset_id again.
func TestRunBackfill_IdempotentOnSecondRun(t *testing.T) {
	ffmpegBinary := requireFFmpegBinary(t)
	pool := openBackfillTestFixture(t)

	const segmentID = int64(8)
	setupBackfillSegment(t, pool, segmentID)

	renderDir := t.TempDir()
	outputRel := "segment-8.mp4"
	generateSolidColorFixtureVideo(t, ffmpegBinary, filepath.Join(renderDir, outputRel), "green", 4)
	insertReadyRenderCache(t, pool, segmentID, "cache-8", outputRel, 4, time.Now())

	storageDir := t.TempDir()
	cfg := backfillTestConfig(pool, renderDir, storageDir, ffmpegBinary)

	firstStats, err := runBackfill(context.Background(), pool, cfg)
	require.NoError(t, err)
	require.Equal(t, 1, firstStats.ProcessedOK)

	assetIDAfterFirstRun := autoPreviewAssetID(t, pool, segmentID)
	require.NotNil(t, assetIDAfterFirstRun)
	assetsAfterFirstRun := countMediaAssets(t, pool)

	secondStats, err := runBackfill(context.Background(), pool, cfg)
	require.NoError(t, err)
	require.Equal(t, 0, secondStats.TotalCandidates, "the already-processed segment must not be a candidate again")
	require.Equal(t, 0, secondStats.ProcessedOK)
	require.Equal(t, 0, secondStats.Failed)

	assetIDAfterSecondRun := autoPreviewAssetID(t, pool, segmentID)
	require.Equal(t, *assetIDAfterFirstRun, *assetIDAfterSecondRun, "the auto preview must not change on a second run")
	require.Equal(t, assetsAfterFirstRun, countMediaAssets(t, pool), "a second run must not create a new media_assets row")
}

// TestRunBackfill_PicksLatestCompletedRender proves D-07: when a segment has two ready
// renders with different completed_at timestamps, the backfill extracts its frame from the
// MOST RECENTLY completed one, regardless of insertion order or source release version. Both
// fixture videos are solid, single colors across their entire duration (red = older, blue =
// newer) so the extracted frame's dominant color proves which render was actually read,
// independent of ffmpeg's low-framerate seek-rounding behavior.
func TestRunBackfill_PicksLatestCompletedRender(t *testing.T) {
	ffmpegBinary := requireFFmpegBinary(t)
	pool := openBackfillTestFixture(t)

	const segmentID = int64(9)
	setupBackfillSegment(t, pool, segmentID)

	renderDir := t.TempDir()
	olderRel := "segment-9-older.mp4"
	newerRel := "segment-9-newer.mp4"
	generateSolidColorFixtureVideo(t, ffmpegBinary, filepath.Join(renderDir, olderRel), "red", 4)
	generateSolidColorFixtureVideo(t, ffmpegBinary, filepath.Join(renderDir, newerRel), "blue", 4)

	older := time.Now().Add(-1 * time.Hour)
	newer := time.Now()
	// Insert the OLDER row with a later cache id but an EARLIER completed_at, and vice versa,
	// so a naive "last inserted" or "highest id" assumption would pick the wrong one --
	// D-07 requires ordering strictly by completed_at.
	insertReadyRenderCache(t, pool, segmentID, "cache-9-newer", newerRel, 4, newer)
	insertReadyRenderCache(t, pool, segmentID, "cache-9-older", olderRel, 4, older)

	storageDir := t.TempDir()
	cfg := backfillTestConfig(pool, renderDir, storageDir, ffmpegBinary)

	stats, err := runBackfill(context.Background(), pool, cfg)
	require.NoError(t, err)
	require.Equal(t, 1, stats.ProcessedOK)

	assetID := autoPreviewAssetID(t, pool, segmentID)
	require.NotNil(t, assetID)

	var storedPath string
	require.NoError(t, pool.QueryRow(context.Background(),
		`SELECT path FROM media_files WHERE media_id = $1`, *assetID).Scan(&storedPath))

	img, err := imaging.Open(storedPath)
	require.NoError(t, err, "extracted preview file must be a decodable image")
	bounds := img.Bounds()
	r, g, b, _ := img.At(bounds.Dx()/2, bounds.Dy()/2).RGBA()
	t.Logf("extracted pixel RGBA: r=%d g=%d b=%d", r, g, b)
	require.Greater(t, b, r, "extracted frame must come from the NEWER (blue) render, not the older (red) one -- D-07")
}
