ALTER TABLE anime
    ADD COLUMN IF NOT EXISTS title_de TEXT,
    ADD COLUMN IF NOT EXISTS title_en TEXT,
    ADD COLUMN IF NOT EXISTS genre TEXT,
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS view_count INTEGER NOT NULL DEFAULT 0;
