ALTER TABLE release_media DROP CONSTRAINT IF EXISTS fk_release_media_release;
ALTER TABLE media_assets DROP CONSTRAINT IF EXISTS fk_media_assets_modified_by;
ALTER TABLE media_assets DROP CONSTRAINT IF EXISTS fk_media_assets_uploaded_by;
DROP INDEX IF EXISTS idx_fansub_group_alias_group;
ALTER TABLE fansub_group_aliases DROP COLUMN IF EXISTS group_id;
ALTER TABLE fansub_groups DROP COLUMN IF EXISTS history_description;
ALTER TABLE fansub_groups DROP COLUMN IF EXISTS closed_year;
ALTER TABLE release_streams DROP CONSTRAINT IF EXISTS release_streams_modified_by_fkey;
ALTER TABLE release_streams DROP COLUMN IF EXISTS modified_by;
ALTER TABLE release_streams DROP COLUMN IF EXISTS modified_at;
DROP INDEX IF EXISTS idx_release_version_group_group;
DROP INDEX IF EXISTS idx_release_version_group_version;
ALTER TABLE release_version_groups DROP COLUMN IF EXISTS fansubgroup_id;
ALTER TABLE release_variants DROP CONSTRAINT IF EXISTS uq_release_variant_filename;
ALTER TABLE release_variants DROP CONSTRAINT IF EXISTS fk_release_variants_modified_by;
ALTER TABLE release_versions DROP CONSTRAINT IF EXISTS fk_release_versions_modified_by;
DROP INDEX IF EXISTS idx_release_source;
DROP INDEX IF EXISTS idx_release_episode;
ALTER TABLE fansub_releases DROP CONSTRAINT IF EXISTS fk_fansub_releases_modified_by;
ALTER TABLE fansub_releases DROP COLUMN IF EXISTS source;
DROP INDEX IF EXISTS uq_episodes_anime_number_type;
DROP INDEX IF EXISTS idx_episode_filler_type;
ALTER TABLE episodes DROP COLUMN IF EXISTS modified_by;
ALTER TABLE episodes DROP COLUMN IF EXISTS modified_at;
ALTER TABLE episodes DROP COLUMN IF EXISTS filler_note;
ALTER TABLE episodes DROP COLUMN IF EXISTS filler_source;
ALTER TABLE episodes DROP COLUMN IF EXISTS filler_type_id;
ALTER TABLE episodes DROP COLUMN IF EXISTS number_text;
DROP INDEX IF EXISTS idx_anime_type_id;
DROP INDEX IF EXISTS idx_anime_slug;
DROP INDEX IF EXISTS uq_anime_slug;
DROP INDEX IF EXISTS uq_anime_anisearch_id;
ALTER TABLE anime DROP COLUMN IF EXISTS modified_by;
ALTER TABLE anime DROP COLUMN IF EXISTS modified_at;
ALTER TABLE anime DROP COLUMN IF EXISTS slug;
ALTER TABLE anime DROP COLUMN IF EXISTS anime_type_id;
