-- Migration 0159: Phase 143 Kriterium 2 remediation.
-- Migrations are append-only in this project, so 0154 itself stays untouched
-- (it remains applied and its 232-row target catalog is unchanged) — but
-- 0154's `up.sql` performed an unconditional table wipe + reinsert with no
-- `ON CONFLICT` clause and an empty no-op `down.sql`, so re-applying it is not
-- provably idempotent and it cannot be reversed. This migration is
-- additive-only (`INSERT ... ON CONFLICT (role_code, action_code) DO NOTHING`,
-- no `DELETE`) specifically because deleting first would silently discard any
-- `role_capabilities` row an admin has since configured via the
-- Capability-Matrix UI (Phase 87, `AdminCapabilityHandler`) that deviates from
-- this exact 232-row baseline catalog. A future "converge exactly to the
-- catalog, discard everything else" operation, if ever genuinely needed,
-- belongs in a documented, backup-first operator script — never inside an
-- unattended append-only migration. This migration establishes the same
-- approved 232-row role_capabilities catalog (byte-identical tuples, same
-- order as 0154) additively: a second `up` application is now a true no-op
-- (the `INSERT ... ON CONFLICT DO NOTHING` has nothing left to insert), and it
-- is reversible without wiping the 12 techadmin rows migration 0153
-- established. `down.sql` deletes exactly the 220 non-techadmin
-- (role_code, action_code) tuples this file's `up.sql` inserts, making the
-- pair a genuinely matched, symmetric additive-insert/scoped-delete unit.
BEGIN;

INSERT INTO role_capabilities (role_code, action_code)
VALUES
    ('co_leader', 'fansub_group.edit'),
    ('co_leader', 'fansub_group.historical_members.link'),
    ('co_leader', 'fansub_group.historical_members.manage'),
    ('co_leader', 'fansub_group.historical_roles.manage'),
    ('co_leader', 'fansub_group.invitations.cancel'),
    ('co_leader', 'fansub_group.invitations.create'),
    ('co_leader', 'fansub_group.invitations.view'),
    ('co_leader', 'fansub_group.links.manage'),
    ('co_leader', 'fansub_group_links.update'),
    ('co_leader', 'fansub_group_media.reorder'),
    ('co_leader', 'fansub_group_media.update'),
    ('co_leader', 'fansub_group_media.upload'),
    ('co_leader', 'fansub_group_media.view'),
    ('co_leader', 'fansub_group.members.manage'),
    ('co_leader', 'fansub_group.members.view'),
    ('co_leader', 'fansub_group.notes.write'),
    ('co_leader', 'fansub_group_page.founding_history_edit'),
    ('co_leader', 'fansub_group_page.general_edit'),
    ('co_leader', 'fansub_group_page.technical_links_edit'),
    ('co_leader', 'review.contribution.decide'),
    ('co_leader', 'review.image.decide'),
    ('co_leader', 'review.text.decide'),
    ('designer', 'fansub_group_media.reorder'),
    ('designer', 'fansub_group_media.update'),
    ('designer', 'fansub_group_media.upload'),
    ('designer', 'fansub_group_media.view'),
    ('designer', 'fansub_group.members.view'),
    ('designer', 'release_version_media.delete_own'),
    ('designer', 'release_version_media.update'),
    ('designer', 'release_version_media.upload'),
    ('designer', 'release_version_media.view'),
    ('designer', 'release_version.segments.manage'),
    ('designer', 'release_version.view'),
    ('designer', 'release.view'),
    ('designer', 'review.image.decide'),
    ('designer', 'review.text.decide'),
    ('editor', 'anime_fansub_project.notes.write'),
    ('editor', 'fansub_group_media.upload'),
    ('editor', 'fansub_group_media.view'),
    ('editor', 'fansub_group.members.view'),
    ('editor', 'release_version_media.delete_own'),
    ('editor', 'release_version_media.update'),
    ('editor', 'release_version_media.upload'),
    ('editor', 'release_version_media.view'),
    ('editor', 'release_version.notes.write'),
    ('editor', 'release_version.segments.manage'),
    ('editor', 'release_version.view'),
    ('editor', 'release.view'),
    ('editor', 'review.image.decide'),
    ('editor', 'review.text.decide'),
    ('encoder', 'fansub_group_media.upload'),
    ('encoder', 'fansub_group_media.view'),
    ('encoder', 'fansub_group.members.view'),
    ('encoder', 'release_version_media.delete_own'),
    ('encoder', 'release_version_media.update'),
    ('encoder', 'release_version_media.upload'),
    ('encoder', 'release_version_media.view'),
    ('encoder', 'release_version.notes.write'),
    ('encoder', 'release_version.segments.manage'),
    ('encoder', 'release_version.view'),
    ('encoder', 'release.view'),
    ('encoder', 'review.contribution.decide'),
    ('encoder', 'review.image.decide'),
    ('encoder', 'review.text.decide'),
    ('fansub_lead', 'anime_fansub_project.notes.write'),
    ('fansub_lead', 'fansub_group.edit'),
    ('fansub_lead', 'fansub_group.historical_members.link'),
    ('fansub_lead', 'fansub_group.historical_members.manage'),
    ('fansub_lead', 'fansub_group.historical_roles.manage'),
    ('fansub_lead', 'fansub_group.invitations.cancel'),
    ('fansub_lead', 'fansub_group.invitations.create'),
    ('fansub_lead', 'fansub_group.invitations.view'),
    ('fansub_lead', 'fansub_group.links.manage'),
    ('fansub_lead', 'fansub_group_links.update'),
    ('fansub_lead', 'fansub_group_media.delete'),
    ('fansub_lead', 'fansub_group_media.reorder'),
    ('fansub_lead', 'fansub_group_media.update'),
    ('fansub_lead', 'fansub_group_media.upload'),
    ('fansub_lead', 'fansub_group_media.view'),
    ('fansub_lead', 'fansub_group.members.manage'),
    ('fansub_lead', 'fansub_group.members.view'),
    ('fansub_lead', 'fansub_group.notes.write'),
    ('fansub_lead', 'fansub_group_page.founding_history_edit'),
    ('fansub_lead', 'fansub_group_page.general_edit'),
    ('fansub_lead', 'fansub_group_page.technical_links_edit'),
    ('fansub_lead', 'release_version_media.delete'),
    ('fansub_lead', 'release_version_media.delete_own'),
    ('fansub_lead', 'release_version_media.update'),
    ('fansub_lead', 'release_version_media.upload'),
    ('fansub_lead', 'release_version_media.view'),
    ('fansub_lead', 'release_version.notes.write'),
    ('fansub_lead', 'release_version.segments.manage'),
    ('fansub_lead', 'release_version.view'),
    ('fansub_lead', 'release.view'),
    ('fansub_lead', 'review.contribution.decide'),
    ('fansub_lead', 'review.image.decide'),
    ('fansub_lead', 'review.text.decide'),
    ('fansub_lead', 'user_group_capability_override.manage'),
    ('founder', 'fansub_group_media.reorder'),
    ('founder', 'fansub_group_media.update'),
    ('founder', 'fansub_group_media.upload'),
    ('founder', 'fansub_group_media.view'),
    ('founder', 'fansub_group.members.manage'),
    ('founder', 'fansub_group.notes.write'),
    ('founder', 'fansub_group_page.founding_history_edit'),
    ('founder', 'review.contribution.decide'),
    ('founder', 'review.image.decide'),
    ('founder', 'review.text.decide'),
    ('gfxler', 'fansub_group_media.reorder'),
    ('gfxler', 'fansub_group_media.update'),
    ('gfxler', 'fansub_group_media.upload'),
    ('gfxler', 'fansub_group_media.view'),
    ('gfxler', 'fansub_group.members.view'),
    ('gfxler', 'release_version.segments.manage'),
    ('gfxler', 'review.image.decide'),
    ('karaoke_fx', 'fansub_group_media.upload'),
    ('karaoke_fx', 'fansub_group_media.view'),
    ('karaoke_fx', 'fansub_group.members.view'),
    ('karaoke_fx', 'release_version_media.delete_own'),
    ('karaoke_fx', 'release_version_media.update'),
    ('karaoke_fx', 'release_version_media.upload'),
    ('karaoke_fx', 'release_version_media.view'),
    ('karaoke_fx', 'release_version.notes.write'),
    ('karaoke_fx', 'release_version.segments.manage'),
    ('karaoke_fx', 'release_version.view'),
    ('karaoke_fx', 'release.view'),
    ('karaoke_fx', 'review.image.decide'),
    ('karaoke_fx', 'review.text.decide'),
    ('project_lead', 'anime_fansub_project.notes.write'),
    ('project_lead', 'fansub_group.edit'),
    ('project_lead', 'fansub_group.links.manage'),
    ('project_lead', 'fansub_group_media.reorder'),
    ('project_lead', 'fansub_group_media.update'),
    ('project_lead', 'fansub_group_media.upload'),
    ('project_lead', 'fansub_group_media.view'),
    ('project_lead', 'fansub_group.members.view'),
    ('project_lead', 'fansub_group.notes.write'),
    ('project_lead', 'release_version_media.delete'),
    ('project_lead', 'release_version_media.delete_own'),
    ('project_lead', 'release_version_media.update'),
    ('project_lead', 'release_version_media.upload'),
    ('project_lead', 'release_version_media.view'),
    ('project_lead', 'release_version.notes.write'),
    ('project_lead', 'release_version.segments.manage'),
    ('project_lead', 'release_version.view'),
    ('project_lead', 'release.view'),
    ('project_lead', 'review.contribution.decide'),
    ('project_lead', 'review.image.decide'),
    ('project_lead', 'review.text.decide'),
    ('project_lead', 'user_group_capability_override.manage'),
    ('quality_checker', 'anime_fansub_project.notes.write'),
    ('quality_checker', 'fansub_group_media.update'),
    ('quality_checker', 'fansub_group_media.upload'),
    ('quality_checker', 'fansub_group_media.view'),
    ('quality_checker', 'fansub_group.members.view'),
    ('quality_checker', 'fansub_group.notes.write'),
    ('quality_checker', 'release_version_media.delete_own'),
    ('quality_checker', 'release_version_media.update'),
    ('quality_checker', 'release_version_media.upload'),
    ('quality_checker', 'release_version_media.view'),
    ('quality_checker', 'release_version.notes.write'),
    ('quality_checker', 'release_version.segments.manage'),
    ('quality_checker', 'release_version.view'),
    ('quality_checker', 'release.view'),
    ('quality_checker', 'review.image.decide'),
    ('quality_checker', 'review.text.decide'),
    ('raw_provider', 'fansub_group_media.update'),
    ('raw_provider', 'fansub_group_media.upload'),
    ('raw_provider', 'fansub_group_media.view'),
    ('raw_provider', 'fansub_group.members.view'),
    ('raw_provider', 'release_version_media.delete_own'),
    ('raw_provider', 'release_version_media.update'),
    ('raw_provider', 'release_version_media.upload'),
    ('raw_provider', 'release_version_media.view'),
    ('raw_provider', 'release_version.notes.write'),
    ('raw_provider', 'release_version.segments.manage'),
    ('raw_provider', 'release_version.view'),
    ('raw_provider', 'release.view'),
    ('raw_provider', 'review.image.decide'),
    ('raw_provider', 'review.text.decide'),
    ('techadmin', 'fansub_group.invitations.cancel'),
    ('techadmin', 'fansub_group.invitations.create'),
    ('techadmin', 'fansub_group.invitations.view'),
    ('techadmin', 'fansub_group.links.manage'),
    ('techadmin', 'fansub_group_links.update'),
    ('techadmin', 'fansub_group_media.update'),
    ('techadmin', 'fansub_group_media.upload'),
    ('techadmin', 'fansub_group_media.view'),
    ('techadmin', 'fansub_group.members.view'),
    ('techadmin', 'fansub_group_page.technical_links_edit'),
    ('techadmin', 'review.contribution.decide'),
    ('techadmin', 'review.image.decide'),
    ('timer', 'fansub_group_media.upload'),
    ('timer', 'fansub_group_media.view'),
    ('timer', 'fansub_group.members.view'),
    ('timer', 'release_version_media.delete_own'),
    ('timer', 'release_version_media.update'),
    ('timer', 'release_version_media.upload'),
    ('timer', 'release_version_media.view'),
    ('timer', 'release_version.notes.write'),
    ('timer', 'release_version.segments.manage'),
    ('timer', 'release_version.view'),
    ('timer', 'release.view'),
    ('timer', 'review.image.decide'),
    ('timer', 'review.text.decide'),
    ('translator', 'fansub_group_media.upload'),
    ('translator', 'fansub_group_media.view'),
    ('translator', 'fansub_group.members.view'),
    ('translator', 'release_version_media.delete_own'),
    ('translator', 'release_version_media.update'),
    ('translator', 'release_version_media.upload'),
    ('translator', 'release_version_media.view'),
    ('translator', 'release_version.notes.write'),
    ('translator', 'release_version.segments.manage'),
    ('translator', 'release_version.view'),
    ('translator', 'release.view'),
    ('translator', 'review.image.decide'),
    ('translator', 'review.text.decide'),
    ('typesetter', 'fansub_group_media.update'),
    ('typesetter', 'fansub_group_media.upload'),
    ('typesetter', 'fansub_group_media.view'),
    ('typesetter', 'fansub_group.members.view'),
    ('typesetter', 'release_version_media.delete_own'),
    ('typesetter', 'release_version_media.update'),
    ('typesetter', 'release_version_media.upload'),
    ('typesetter', 'release_version_media.view'),
    ('typesetter', 'release_version.notes.write'),
    ('typesetter', 'release_version.segments.manage'),
    ('typesetter', 'release_version.view'),
    ('typesetter', 'release.view'),
    ('typesetter', 'review.image.decide'),
    ('typesetter', 'review.text.decide')
ON CONFLICT (role_code, action_code) DO NOTHING;

COMMIT;
