package repository_test

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http/httptest"
	"net/url"
	"sync"
	"testing"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/require"
	"team4s.v3/backend/internal/handlers"
	"team4s.v3/backend/internal/models"
	"team4s.v3/backend/internal/repository"
	"team4s.v3/backend/internal/testsupport"
)

type episodePublicQuery struct {
	SQL  string
	Rows int64
}
type episodePublicTracer struct {
	mu      sync.Mutex
	queries []*episodePublicQuery
}
type episodePublicTraceKey struct{}

func (tr *episodePublicTracer) TraceQueryStart(ctx context.Context, _ *pgx.Conn, d pgx.TraceQueryStartData) context.Context {
	q := &episodePublicQuery{SQL: d.SQL}
	tr.mu.Lock()
	tr.queries = append(tr.queries, q)
	tr.mu.Unlock()
	return context.WithValue(ctx, episodePublicTraceKey{}, q)
}
func (tr *episodePublicTracer) TraceQueryEnd(ctx context.Context, _ *pgx.Conn, d pgx.TraceQueryEndData) {
	tr.mu.Lock()
	defer tr.mu.Unlock()
	ctx.Value(episodePublicTraceKey{}).(*episodePublicQuery).Rows = d.CommandTag.RowsAffected()
}
func (tr *episodePublicTracer) reset() { tr.mu.Lock(); defer tr.mu.Unlock(); tr.queries = nil }

func openEpisodeVersionPublicFixture(t *testing.T) (*pgxpool.Pool, *episodePublicTracer) {
	t.Helper()
	// Explicit guarded test DSN, unique schema/search_path and scoped cleanup;
	// never application DATABASE_URL. Schema additions exist only in this fixture.
	fixture := testsupport.OpenPhase117Postgres(t)
	_, err := fixture.Exec(context.Background(), `
ALTER TABLE anime ADD COLUMN status TEXT NOT NULL DEFAULT 'done';
ALTER TABLE fansub_groups ADD COLUMN slug TEXT, ADD COLUMN logo_url TEXT;
ALTER TABLE fansub_releases ADD COLUMN source_id BIGINT, ADD COLUMN source BIGINT,
    ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE release_versions ADD COLUMN production_started_on TIMESTAMPTZ,
    ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE release_variants ADD COLUMN IF NOT EXISTS video_quality TEXT, ADD COLUMN IF NOT EXISTS resolution TEXT,
    ADD COLUMN IF NOT EXISTS subtitle_type TEXT, ADD COLUMN crc32 TEXT, ADD COLUMN filename TEXT, ADD COLUMN IF NOT EXISTS container TEXT,
    ADD COLUMN IF NOT EXISTS video_codec TEXT, ADD COLUMN IF NOT EXISTS audio_codec TEXT, ADD COLUMN created_at TIMESTAMPTZ DEFAULT NOW(),
    ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW();
CREATE TABLE release_variant_episodes (release_variant_id BIGINT REFERENCES release_variants(id),
    episode_id BIGINT REFERENCES episodes(id), position INT, PRIMARY KEY(release_variant_id, episode_id));
CREATE TABLE release_sources (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT, source_type TEXT, type TEXT);
CREATE TABLE stream_types (id BIGINT PRIMARY KEY, name TEXT);
INSERT INTO stream_types VALUES (1, 'episode');
ALTER TABLE release_streams ADD COLUMN stream_type_id BIGINT DEFAULT 1, ADD COLUMN IF NOT EXISTS audio_language_id BIGINT,
    ADD COLUMN IF NOT EXISTS subtitle_language_id BIGINT, ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE stream_sources ADD COLUMN metadata JSONB NOT NULL DEFAULT '{}';
ALTER TABLE stream_sources ADD CONSTRAINT fixture_stream_source_identity UNIQUE(provider_type, external_id);
ALTER TABLE fansub_releases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 10000);
ALTER TABLE release_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 20000);
ALTER TABLE release_variants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 30000);
ALTER TABLE stream_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 40000);
ALTER TABLE release_streams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 50000);
INSERT INTO anime (id,status) VALUES (1,'done'),(2,'done'),(3,'disabled'),(4,'done'),(5,'done'),(6,'done');
INSERT INTO episodes (id,anime_id,episode_number,title) VALUES
 (11,1,'1','Episode one'),(12,1,'2','Neutral mixed'),(13,1,'1','Same number, another neutral episode'),
 (14,1,'3','Equal IDs'),(41,4,'1','Many variants'),(42,4,'2','Neutral after many'),(51,5,'1','Only neutral'),(61,6,'1','Foreign');
INSERT INTO fansub_groups (id,slug,name) VALUES (1,'stored-one','First group'),(2,'stored-two','Second group');
INSERT INTO fansub_releases (id,episode_id) VALUES (1,11),(2,14),(3,13),(4,41),(6,61);
INSERT INTO release_versions (id,release_id,version,title,production_started_on,release_date) VALUES
 (10,1,'v1','First release','2020-01-01','2020-02-01'),(11,1,'v2','Second release',NULL,'2021-02-01'),
 (13,3,'v1','No variant',NULL,NULL),(200,2,'v1','Equal ID release',NULL,NULL),
 (40,4,'v1','Large release',NULL,NULL),(20,6,'v1','Foreign release',NULL,NULL);
INSERT INTO release_variants (id,release_version_id,video_quality,subtitle_type,crc32,duration_seconds) VALUES
 (100,10,'1080p','softsub','ABCDEF01',1440),(101,11,'720p','hardsub','01234567',1430),
 (200,200,'480p','softsub',NULL,1400),(10,20,'1080p','softsub',NULL,1400);
INSERT INTO release_variants (id,release_version_id,video_quality,subtitle_type)
 SELECT 1000+n,40,'1080p','softsub' FROM generate_series(0,124) n;
INSERT INTO release_variant_episodes SELECT rv.id,fr.episode_id,1 FROM release_variants rv
 JOIN release_versions rev ON rev.id=rv.release_version_id JOIN fansub_releases fr ON fr.id=rev.release_id;
INSERT INTO release_version_groups VALUES (10,1),(10,2),(11,2),(200,1),(40,1),(40,2),(20,2);
INSERT INTO stream_sources (id,provider_type,external_id,url) VALUES
 (1,'jellyfin','foreign','https://fixture.invalid/foreign'),(2,'jellyfin','own','https://fixture.invalid/own'),
 (3,'external','second','https://fixture.invalid/second');
INSERT INTO release_streams (id,variant_id,stream_source_id) VALUES (1,10,1),(2,100,2),(3,100,3);
INSERT INTO theme_types (id,name) VALUES (1,'OP');
INSERT INTO themes (id,anime_id,theme_type_id) VALUES (1,1,1);
INSERT INTO theme_segments (id,theme_id,fansub_group_id,version,start_episode,end_episode,source_type,source_ref)
 VALUES (1,1,1,'v1',1,1,'release_asset',''),
        (2,1,2,'v99',99,100,'release_asset','assigned-outside-range'),
        (3,1,2,'v2',50,50,'release_asset','   ');
INSERT INTO theme_segment_assignments (theme_segment_id,release_version_id) VALUES (2,10),(3,11);
`)
	require.NoError(t, err)
	tr := &episodePublicTracer{}
	cfg := fixture.Config()
	cfg.ConnConfig.Tracer = tr
	cfg.MaxConns = 1
	pool, err := pgxpool.NewWithConfig(context.Background(), cfg)
	require.NoError(t, err)
	t.Cleanup(pool.Close)
	require.NoError(t, pool.Ping(context.Background()))
	tr.reset()
	return pool, tr
}

type publicEpisodeFixture struct {
	EpisodeID        int64            `json:"episode_id"`
	EpisodeNumber    int32            `json:"episode_number"`
	EpisodeTitle     string           `json:"episode_title"`
	VersionCount     int              `json:"version_count"`
	DefaultVersionID *int64           `json:"default_version_id"`
	Versions         []map[string]any `json:"versions"`
}
type publicEpisodeEnvelope struct {
	Data struct {
		AnimeID    int64                  `json:"anime_id"`
		Episodes   []publicEpisodeFixture `json:"episodes"`
		Pagination struct {
			HasMore    bool    `json:"has_more"`
			NextCursor *string `json:"next_cursor"`
			RowLimit   int     `json:"row_limit"`
		} `json:"pagination"`
	} `json:"data"`
}

func episodePublicRequest(t *testing.T, pool *pgxpool.Pool, path string, status int) ([]byte, publicEpisodeEnvelope) {
	t.Helper()
	gin.SetMode(gin.TestMode)
	h := handlers.NewFansubHandler(repository.NewFansubRepository(pool), repository.NewEpisodeVersionRepository(pool), nil, "admin", handlers.FansubProxyConfig{})
	router := gin.New()
	router.GET("/anime/:id/episodes", h.ListGroupedEpisodes)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, httptest.NewRequest("GET", path, nil))
	require.Equal(t, status, w.Code, w.Body.String())
	var result publicEpisodeEnvelope
	if status == 200 {
		require.NoError(t, json.Unmarshal(w.Body.Bytes(), &result))
	}
	return w.Body.Bytes(), result
}
func assertPublicBudget(t *testing.T, tr *episodePublicTracer, limit int) {
	t.Helper()
	require.Len(t, tr.queries, 2, "existence plus one bounded query, including any metadata SQL")
	require.EqualValues(t, 1, tr.queries[0].Rows)
	require.LessOrEqual(t, tr.queries[1].Rows, int64(limit+1))
	require.NotContains(t, tr.queries[1].SQL, "theme_segment")
	require.NotContains(t, tr.queries[1].SQL, "release_streams")
	t.Logf("SQL statements=%d returned rows=%d+%d (inventory budget %d+1)", len(tr.queries), tr.queries[0].Rows, tr.queries[1].Rows, limit)
}

func TestEpisodeVersionPublicMixedAndIdentity(t *testing.T) {
	pool, tr := openEpisodeVersionPublicFixture(t)
	raw, page := episodePublicRequest(t, pool, "/anime/1/episodes?projection=public", 200)
	require.Equal(t, 24, page.Data.Pagination.RowLimit)
	require.False(t, page.Data.Pagination.HasMore)
	require.Nil(t, page.Data.Pagination.NextCursor)
	require.Len(t, page.Data.Episodes, 4)
	require.Equal(t, []int64{11, 13, 12, 14}, []int64{page.Data.Episodes[0].EpisodeID, page.Data.Episodes[1].EpisodeID, page.Data.Episodes[2].EpisodeID, page.Data.Episodes[3].EpisodeID})
	require.Len(t, page.Data.Episodes[0].Versions, 2, "multiple streams/groups cannot fan out variants")
	first := page.Data.Episodes[0].Versions[0]
	require.EqualValues(t, 100, first["id"])
	require.EqualValues(t, 100, first["variant_id"])
	require.EqualValues(t, 10, first["release_version_id"])
	require.Len(t, first["fansub_groups"], 2)
	require.Equal(t, 2, page.Data.Episodes[0].VersionCount)
	require.EqualValues(t, 100, *page.Data.Episodes[0].DefaultVersionID)
	require.Empty(t, page.Data.Episodes[1].Versions)
	require.NotNil(t, page.Data.Episodes[1].Versions)
	require.Empty(t, page.Data.Episodes[2].Versions)
	require.Nil(t, page.Data.Episodes[2].DefaultVersionID)
	equal := page.Data.Episodes[3].Versions[0]
	require.Equal(t, equal["variant_id"], equal["release_version_id"])
	for _, field := range []string{"media_provider", "media_item_id", "stream_url", "segment_count", "has_segment_asset", "duration_seconds", "crc32", "created_at", "updated_at", "covered_episode_numbers"} {
		require.NotContains(t, first, field)
	}
	assertPublicBudget(t, tr, 24)
	t.Logf("mixed payload bytes=%d", len(raw))
	tr.reset()
	_, foreign := episodePublicRequest(t, pool, "/anime/6/episodes?projection=public", 200)
	require.EqualValues(t, 10, foreign.Data.Episodes[0].Versions[0]["variant_id"])
	require.EqualValues(t, 20, foreign.Data.Episodes[0].Versions[0]["release_version_id"])
	assertPublicBudget(t, tr, 24)
}

func TestEpisodeVersionPublicAtomicPages(t *testing.T) {
	pool, tr := openEpisodeVersionPublicFixture(t)
	for _, limit := range []int{1, 24, 100} {
		t.Run(fmt.Sprint(limit), func(t *testing.T) {
			seen := map[string]bool{}
			cursor := ""
			pages := 0
			totalBytes := 0
			for {
				tr.reset()
				raw, page := episodePublicRequest(t, pool, fmt.Sprintf("/anime/4/episodes?projection=public&limit=%d&cursor=%s", limit, url.QueryEscape(cursor)), 200)
				rows := 0
				for _, episode := range page.Data.Episodes {
					if episode.EpisodeID == 41 {
						require.Equal(t, 125, episode.VersionCount)
						require.EqualValues(t, 1000, *episode.DefaultVersionID)
					}
					if len(episode.Versions) == 0 {
						key := fmt.Sprintf("%d:0", episode.EpisodeID)
						require.False(t, seen[key])
						seen[key] = true
						rows++
					}
					for _, variant := range episode.Versions {
						key := fmt.Sprintf("%d:%.0f", episode.EpisodeID, variant["variant_id"])
						require.False(t, seen[key])
						seen[key] = true
						rows++
					}
				}
				require.LessOrEqual(t, rows, limit)
				assertPublicBudget(t, tr, limit)
				pages++
				totalBytes += len(raw)
				if !page.Data.Pagination.HasMore {
					require.Nil(t, page.Data.Pagination.NextCursor)
					break
				}
				require.NotNil(t, page.Data.Pagination.NextCursor)
				require.NotEmpty(t, *page.Data.Pagination.NextCursor)
				require.NotEqual(t, cursor, *page.Data.Pagination.NextCursor)
				cursor = *page.Data.Pagination.NextCursor
				require.LessOrEqual(t, pages, 126)
			}
			require.Len(t, seen, 126)
			require.True(t, seen["42:0"])
			t.Logf("limit=%d pages=%d atomic rows=%d total serialized bytes=%d", limit, pages, len(seen), totalBytes)
		})
	}
	tr.reset()
	_, first := episodePublicRequest(t, pool, "/anime/1/episodes?projection=public&limit=1", 200)
	require.NotNil(t, first.Data.Pagination.NextCursor)
	cursor := *first.Data.Pagination.NextCursor
	tr.reset()
	episodePublicRequest(t, pool, "/anime/4/episodes?projection=public&cursor="+url.QueryEscape(cursor), 400)
	require.Empty(t, tr.queries, "foreign anime cursor must fail before SQL")
}

func TestEpisodeVersionPublicEmptyAndVisibility(t *testing.T) {
	pool, tr := openEpisodeVersionPublicFixture(t)
	_, empty := episodePublicRequest(t, pool, "/anime/2/episodes?projection=public", 200)
	require.NotNil(t, empty.Data.Episodes)
	require.Empty(t, empty.Data.Episodes)
	require.False(t, empty.Data.Pagination.HasMore)
	assertPublicBudget(t, tr, 24)
	tr.reset()
	_, neutral := episodePublicRequest(t, pool, "/anime/5/episodes?projection=public", 200)
	require.Len(t, neutral.Data.Episodes, 1)
	require.EqualValues(t, 51, neutral.Data.Episodes[0].EpisodeID)
	require.NotNil(t, neutral.Data.Episodes[0].Versions)
	require.Empty(t, neutral.Data.Episodes[0].Versions)
	assertPublicBudget(t, tr, 24)
	for _, id := range []int{3, 999} {
		tr.reset()
		episodePublicRequest(t, pool, fmt.Sprintf("/anime/%d/episodes?projection=public", id), 404)
		require.Len(t, tr.queries, 1)
	}
}

func TestEpisodeVersionPublicFullAssignmentAndWrites(t *testing.T) {
	pool, _ := openEpisodeVersionPublicFixture(t)
	ctx := context.Background()
	repo := repository.NewEpisodeVersionRepository(pool)
	for _, includeFansubs := range []bool{true, false} {
		data, err := repo.ListGroupedByAnimeID(ctx, 1, true, includeFansubs)
		require.NoError(t, err)
		for _, episode := range data.Episodes {
			for _, v := range episode.Versions {
				if v.ID == 100 {
					require.EqualValues(t, 1, v.SegmentCount)
					require.True(t, v.HasSegmentAsset)
				}
				if v.ID == 101 {
					require.EqualValues(t, 1, v.SegmentCount)
					require.False(t, v.HasSegmentAsset)
				}
			}
		}
	}
	item, err := repo.GetByID(ctx, 100)
	require.NoError(t, err)
	encoded, err := json.Marshal(item)
	require.NoError(t, err)
	var fields map[string]any
	require.NoError(t, json.Unmarshal(encoded, &fields))
	for _, key := range []string{"id", "variant_id", "release_version_id", "release_version", "fansub_groups", "media_provider", "media_item_id", "covered_episode_numbers", "video_quality", "subtitle_type", "crc32", "production_started_on", "release_date", "stream_url", "segment_count", "has_segment_asset", "duration_seconds", "created_at", "updated_at"} {
		require.Contains(t, fields, key)
	}
	require.EqualValues(t, 100, fields["variant_id"])
	require.EqualValues(t, 10, fields["release_version_id"])
	require.EqualValues(t, 1, item.SegmentCount)
	require.True(t, item.HasSegmentAsset)
	counts, err := repo.ListGroupedByAnimeID(ctx, 1, false, false)
	require.NoError(t, err)
	for _, episode := range counts.Episodes {
		require.NotNil(t, episode.Versions)
		require.Empty(t, episode.Versions)
		require.Nil(t, episode.DefaultVersionID)
	}
	title, quality, subtitle, crc, stream := "Created release.mkv", "1080p", "softsub", "1234ABCD", "https://fixture.invalid/created"
	date := time.Date(2021, 2, 3, 0, 0, 0, 0, time.UTC)
	duration := int32(1441)
	created, err := repo.Create(ctx, models.EpisodeVersionCreateInput{AnimeID: 1, EpisodeNumber: 2, Title: &title, MediaProvider: "jellyfin", MediaItemID: "created", VideoQuality: &quality, SubtitleType: &subtitle, CRC32: &crc, StreamURL: &stream, ReleaseDate: &date, DurationSeconds: &duration})
	require.NoError(t, err)
	require.Equal(t, "created", created.MediaItemID)
	require.Equal(t, &crc, created.CRC32)
	require.Equal(t, &duration, created.DurationSeconds)
	encoded, err = json.Marshal(created)
	require.NoError(t, err)
	require.NoError(t, json.Unmarshal(encoded, &fields))
	require.EqualValues(t, created.ID, fields["variant_id"])
	require.NotEqual(t, fields["variant_id"], fields["release_version_id"])
	title = "Changed title"
	started := date.AddDate(0, 0, -1)
	patched, err := repo.Update(ctx, created.ID, models.EpisodeVersionPatchInput{Title: models.OptionalString{Set: true, Value: &title}, ProductionStartedOn: models.OptionalTime{Set: true, Value: &started}})
	require.NoError(t, err)
	require.Equal(t, &title, patched.Title)
	require.Equal(t, &crc, patched.CRC32)
	require.Equal(t, &stream, patched.StreamURL)
	require.True(t, patched.ProductionStartedOn.Equal(started))
}

func TestEpisodeVersionPublicRawQueryCompatibility(t *testing.T) {
	pool, tr := openEpisodeVersionPublicFixture(t)
	for _, suffix := range []string{"", "?ignored=%ZZ", "?includeVersions=true&includeFansubs=true&ignored=%ZZ"} {
		_, full := episodePublicRequest(t, pool, "/anime/1/episodes"+suffix, 200)
		require.NotEmpty(t, full.Data.Episodes)
	}
	_, first := episodePublicRequest(t, pool, "/anime/4/episodes?projection=public&limit=24&ignored=%ZZ", 200)
	require.NotNil(t, first.Data.Pagination.NextCursor)
	tr.reset()
	_, second := episodePublicRequest(t, pool, "/anime/4/episodes?projection=public&limit=24&cursor="+url.QueryEscape(*first.Data.Pagination.NextCursor)+"&ignored=%ZZ", 200)
	require.NotEqual(t, first.Data.Episodes[0].Versions[0]["variant_id"], second.Data.Episodes[0].Versions[0]["variant_id"])
	assertPublicBudget(t, tr, 24)
}
