package repository

import (
 "context"
 "fmt"
 "testing"
 "github.com/jackc/pgx/v5"
 "github.com/jackc/pgx/v5/pgxpool"
 "github.com/stretchr/testify/require"
 "team4s.v3/backend/internal/models"
)

func openEpisodeImportSourceFixture(t *testing.T)*pgxpool.Pool{
 t.Helper();pool:=openJellyfinSourceFixture(t)
 _,err:=pool.Exec(context.Background(),`
 ALTER TABLE episodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
 ALTER TABLE episodes ADD COLUMN status TEXT, ADD COLUMN episode_type_id BIGINT, ADD COLUMN number INT,
 ADD COLUMN number_text TEXT, ADD COLUMN filler_type_id BIGINT, ADD COLUMN filler_source TEXT, ADD COLUMN filler_note TEXT,
 ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
 ALTER TABLE fansub_groups ADD COLUMN slug TEXT UNIQUE, ADD COLUMN status TEXT DEFAULT 'active';
 ALTER TABLE fansub_releases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
 ALTER TABLE fansub_releases ADD COLUMN source_id BIGINT, ADD COLUMN source BIGINT,
 ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
 ALTER TABLE release_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
 ALTER TABLE release_versions ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
 ALTER TABLE release_variants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
 ALTER TABLE release_variants ADD COLUMN container TEXT, ADD COLUMN filename TEXT, ADD COLUMN resolution TEXT,
 ADD COLUMN video_quality TEXT, ADD COLUMN video_codec TEXT, ADD COLUMN audio_codec TEXT,
 ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
 ALTER TABLE release_streams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
 ALTER TABLE release_streams ADD COLUMN stream_type_id BIGINT, ADD COLUMN audio_language_id BIGINT, ADD COLUMN subtitle_language_id BIGINT,
 ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
 CREATE TABLE episode_types(id BIGINT PRIMARY KEY,name TEXT);INSERT INTO episode_types VALUES(1,'episode');
 CREATE TABLE stream_types(id BIGINT PRIMARY KEY,name TEXT);INSERT INTO stream_types VALUES(1,'episode');
 CREATE TABLE episode_filler_types(id BIGINT PRIMARY KEY,name TEXT);INSERT INTO episode_filler_types VALUES(1,'unknown');
 CREATE TABLE languages(id BIGINT PRIMARY KEY,code TEXT);INSERT INTO languages VALUES(1,'de'),(2,'en'),(3,'ja');
 CREATE TABLE episode_titles(episode_id BIGINT REFERENCES episodes(id),language_id BIGINT,title TEXT,PRIMARY KEY(episode_id,language_id));
 CREATE TABLE release_sources(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT UNIQUE,source_type TEXT,type TEXT);
 CREATE TABLE release_variant_episodes(release_variant_id BIGINT REFERENCES release_variants(id),episode_id BIGINT REFERENCES episodes(id),position INT,PRIMARY KEY(release_variant_id,episode_id));
 CREATE TABLE anime_fansub_groups(anime_id BIGINT REFERENCES anime(id),fansub_group_id BIGINT REFERENCES fansub_groups(id),is_primary BOOLEAN,notes TEXT,PRIMARY KEY(anime_id,fansub_group_id));
 CREATE TABLE fixture_crew_notes(release_version_id BIGINT REFERENCES release_versions(id),fansub_group_id BIGINT REFERENCES fansub_groups(id));
 INSERT INTO anime(id)VALUES(1),(2);INSERT INTO fansub_groups(id,name,slug)VALUES(1,'Group','group');
 `);require.NoError(t,err);return pool
}
type sourceFixtureCrewSeeder struct{}
func (sourceFixtureCrewSeeder) SeedCreatedReleaseInTx(ctx context.Context,tx pgx.Tx,version,group int64)error{
 _,err:=tx.Exec(ctx,"INSERT INTO fixture_crew_notes VALUES($1,$2)",version,group);return err
}
func episodeSourceInput()models.EpisodeImportApplyInput{
 str:=func(s string)*string{return &s};duration:=int32(1234);group:=int64(1);index:=int32(1)
 return models.EpisodeImportApplyInput{AnimeID:1,
 CanonicalEpisodes:[]models.EpisodeImportCanonicalEpisode{{EpisodeNumber:1,TitlesByLanguage:map[string]string{"de":"Folge eins"}}},
 MediaCandidates:[]models.EpisodeImportMediaCandidate{{MediaItemID:"actual-item",MediaSourceID:"source-a",Path:"/anime/a.mkv",
 FileName:"a.mkv",Container:str("matroska"),VideoQuality:str("1080p"),VideoCodec:str("hevc"),AudioCodec:str("flac"),
 DurationSeconds:&duration,StreamURL:str("https://fixture.invalid/Videos/actual-item/stream"),StreamsComplete:true,SelectedAudioIndex:&index,
 AudioTracks:[]models.JellyfinAudioTrack{{Index:1,Codec:"flac"}},SubtitleTracks:[]models.JellyfinSubtitleTrack{{Index:2,Codec:"ass"}}}},
 Mappings:[]models.EpisodeImportMappingRow{{MediaItemID:"actual-item",MediaSourceID:"source-a",Status:models.EpisodeImportMappingStatusConfirmed,TargetEpisodeNumbers:[]int32{1},FansubGroups:[]models.SelectedFansubGroupInput{{ID:&group}}}}}
}
func sourceGraphState(t *testing.T,pool *pgxpool.Pool)map[string]string{
 t.Helper();result:=map[string]string{}
 for _,table:=range []string{"episodes","episode_titles","fansub_releases","release_versions","release_variants","release_streams","stream_sources","release_variant_episodes","release_version_groups","anime_fansub_groups","fixture_crew_notes"}{
 var value string;require.NoError(t,pool.QueryRow(context.Background(),fmt.Sprintf("SELECT COALESCE(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb)::text FROM %s t",table)).Scan(&value));result[table]=value
 };return result
}
func TestEpisodeImportSourceCreateRepeatAndInitialBinding(t *testing.T){
 pool:=openEpisodeImportSourceFixture(t);ctx:=context.Background();repo:=NewEpisodeImportRepository(pool,sourceFixtureCrewSeeder{});input:=episodeSourceInput()
 result,err:=repo.Apply(ctx,input);require.NoError(t,err);require.EqualValues(t,1,result.VersionsCreated)
 var container,filename,video,audio string;var duration int
 require.NoError(t,pool.QueryRow(ctx,"SELECT container,filename,video_codec,audio_codec,duration_seconds FROM release_variants").Scan(&container,&filename,&video,&audio,&duration))
 require.Equal(t,"matroska",container);require.Equal(t,"a.mkv",filename);require.Equal(t,"hevc",video);require.Equal(t,"flac",audio);require.Equal(t,1234,duration)
 bindings,err:=repo.GetJellyfinSourceBindings(ctx,[]string{"actual-item"});require.NoError(t,err);require.Equal(t,"source-a",bindings["actual-item"].MediaSourceID);require.Nil(t,bindings["actual-item"].AudioTracks[0].Language)
 result,err=repo.Apply(ctx,input);require.NoError(t,err);require.EqualValues(t,0,result.VersionsCreated);require.EqualValues(t,1,result.VersionsUpdated)
 for table:=range sourceGraphState(t,pool){ var count int;require.NoError(t,pool.QueryRow(ctx,"SELECT count(*) FROM "+table).Scan(&count));require.Equal(t,1,count,table) }
 // Explicit reapply establishes missing namespace on an existing item; no backfill.
 _,err=pool.Exec(ctx,"UPDATE stream_sources SET metadata='{}'");require.NoError(t,err)
 _,err=repo.Apply(ctx,input);require.NoError(t,err)
 bindings,err=repo.GetJellyfinSourceBindings(ctx,[]string{"actual-item"});require.NoError(t,err);require.Equal(t,"source-a",bindings["actual-item"].MediaSourceID)
}
func TestEpisodeImportSourceRejectsAndRollsBack(t *testing.T){
 for _,scenario:=range []string{"wrong anime","duplicate candidate","absent candidate","stale source","incomplete B","new incomplete item","mapping mismatch"}{
 t.Run(scenario,func(t *testing.T){
 pool:=openEpisodeImportSourceFixture(t);ctx:=context.Background();repo:=NewEpisodeImportRepository(pool,sourceFixtureCrewSeeder{})
 _,err:=repo.Apply(ctx,episodeSourceInput());require.NoError(t,err);before:=sourceGraphState(t,pool);input:=episodeSourceInput()
 switch scenario{
 case "wrong anime":input.AnimeID=2
 case "duplicate candidate":input.MediaCandidates=append(input.MediaCandidates,input.MediaCandidates[0])
 case "absent candidate":input.MediaCandidates=nil
 case "stale source","incomplete B":input.MediaCandidates[0].MediaSourceID="source-b";input.MediaCandidates[0].Path="/anime/b.mkv";input.Mappings[0].MediaSourceID="source-b";input.MediaCandidates[0].StreamsComplete=scenario=="stale source"
 case "new incomplete item":input.MediaCandidates[0].MediaItemID="new-item";input.Mappings[0].MediaItemID="new-item";input.MediaCandidates[0].StreamsComplete=false
 case "mapping mismatch":input.Mappings[0].MediaSourceID="source-b"
 }
 _,err=repo.Apply(ctx,input);require.Error(t,err);require.Equal(t,before,sourceGraphState(t,pool),"every graph table including timestamps must roll back")
 })
 }
}
