package repository_test

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http/httptest"
	"net/url"
	"path/filepath"
	"sync"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/require"
	"team4s.v3/backend/internal/handlers"
	"team4s.v3/backend/internal/repository"
	"team4s.v3/backend/internal/testsupport"
)

type episodePublicQuery struct {
	SQL  string
	Rows int64
}
type episodePublicTracer struct {
	mu      sync.Mutex
	queries []*episodePublicQuery
}
type episodePublicTraceKey struct{}

func (tr *episodePublicTracer) TraceQueryStart(ctx context.Context, _ *pgx.Conn, d pgx.TraceQueryStartData) context.Context {
	q := &episodePublicQuery{SQL: d.SQL}
	tr.mu.Lock()
	tr.queries = append(tr.queries, q)
	tr.mu.Unlock()
	return context.WithValue(ctx, episodePublicTraceKey{}, q)
}
func (tr *episodePublicTracer) TraceQueryEnd(ctx context.Context, _ *pgx.Conn, d pgx.TraceQueryEndData) {
	tr.mu.Lock()
	defer tr.mu.Unlock()
	ctx.Value(episodePublicTraceKey{}).(*episodePublicQuery).Rows = d.CommandTag.RowsAffected()
}
func (tr *episodePublicTracer) reset() { tr.mu.Lock(); defer tr.mu.Unlock(); tr.queries = nil }

func openEpisodeVersionPublicFixture(t *testing.T) (*pgxpool.Pool, *episodePublicTracer) {
	t.Helper()
	// Explicit guarded test DSN, unique schema/search_path and scoped cleanup;
	// never application DATABASE_URL. Schema additions exist only in this fixture.
	fixture := testsupport.OpenPhase117Postgres(t)
	_, err := fixture.Exec(context.Background(), `
ALTER TABLE anime ADD COLUMN status TEXT NOT NULL DEFAULT 'done';
ALTER TABLE fansub_groups ADD COLUMN slug TEXT, ADD COLUMN logo_url TEXT;
ALTER TABLE fansub_releases ADD COLUMN source_id BIGINT, ADD COLUMN source BIGINT,
    ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE release_versions ADD COLUMN production_started_on TIMESTAMPTZ,
    ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE release_variants ADD COLUMN IF NOT EXISTS video_quality TEXT, ADD COLUMN IF NOT EXISTS resolution TEXT,
    ADD COLUMN IF NOT EXISTS subtitle_type TEXT, ADD COLUMN crc32 TEXT, ADD COLUMN filename TEXT, ADD COLUMN IF NOT EXISTS container TEXT,
    ADD COLUMN IF NOT EXISTS video_codec TEXT, ADD COLUMN IF NOT EXISTS audio_codec TEXT, ADD COLUMN created_at TIMESTAMPTZ DEFAULT NOW(),
    ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW();
CREATE TABLE release_variant_episodes (release_variant_id BIGINT REFERENCES release_variants(id),
    episode_id BIGINT REFERENCES episodes(id), position INT, PRIMARY KEY(release_variant_id, episode_id));
CREATE TABLE release_sources (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT, source_type TEXT, type TEXT);
CREATE TABLE stream_types (id BIGINT PRIMARY KEY, name TEXT);
INSERT INTO stream_types VALUES (1, 'episode');
ALTER TABLE release_streams ADD COLUMN stream_type_id BIGINT DEFAULT 1, ADD COLUMN IF NOT EXISTS audio_language_id BIGINT,
    ADD COLUMN IF NOT EXISTS subtitle_language_id BIGINT, ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE stream_sources ADD COLUMN metadata JSONB NOT NULL DEFAULT '{}';
ALTER TABLE stream_sources ADD CONSTRAINT uq_stream_sources_provider_external UNIQUE NULLS NOT DISTINCT(provider_type, external_id);
ALTER TABLE fansub_releases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 10000);
ALTER TABLE release_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 20000);
ALTER TABLE release_variants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 30000);
ALTER TABLE stream_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 40000);
ALTER TABLE release_streams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 50000);
INSERT INTO anime (id,status) VALUES (1,'done'),(2,'done'),(3,'disabled'),(4,'done'),(5,'done'),(6,'done');
INSERT INTO episodes (id,anime_id,episode_number,title) VALUES
 (11,1,'1','Episode one'),(12,1,'2','Neutral mixed'),(13,1,'1','Same number, another neutral episode'),
 (14,1,'3','Equal IDs'),(41,4,'1','Many variants'),(42,4,'2','Neutral after many'),(51,5,'1','Only neutral'),(61,6,'1','Foreign');
INSERT INTO fansub_groups (id,slug,name) VALUES (1,'stored-one','First group'),(2,'stored-two','Second group');
INSERT INTO fansub_releases (id,episode_id) VALUES (1,11),(2,14),(3,13),(4,41),(6,61);
INSERT INTO release_versions (id,release_id,version,title,production_started_on,release_date) VALUES
 (10,1,'v1','First release','2020-01-01','2020-02-01'),(11,1,'v2','Second release',NULL,'2021-02-01'),
 (13,3,'v1','No variant',NULL,NULL),(200,2,'v1','Equal ID release',NULL,NULL),
 (40,4,'v1','Large release',NULL,NULL),(20,6,'v1','Foreign release',NULL,NULL);
INSERT INTO release_variants (id,release_version_id,video_quality,subtitle_type,crc32,duration_seconds) VALUES
 (100,10,'1080p','softsub','ABCDEF01',1440),(101,11,'720p','hardsub','01234567',1430),
 (200,200,'480p','softsub',NULL,1400),(10,20,'1080p','softsub',NULL,1400);
INSERT INTO release_variants (id,release_version_id,video_quality,subtitle_type)
 SELECT 1000+n,40,'1080p','softsub' FROM generate_series(0,124) n;
INSERT INTO release_variant_episodes SELECT rv.id,fr.episode_id,1 FROM release_variants rv
 JOIN release_versions rev ON rev.id=rv.release_version_id JOIN fansub_releases fr ON fr.id=rev.release_id;
INSERT INTO release_version_groups VALUES (10,1),(10,2),(11,2),(200,1),(40,1),(40,2),(20,2);
INSERT INTO stream_sources (id,provider_type,external_id,url) VALUES
 (1,'jellyfin','foreign','https://fixture.invalid/foreign'),(2,'jellyfin','own','https://fixture.invalid/own'),
 (3,'external','second','https://fixture.invalid/second');
INSERT INTO release_streams (id,variant_id,stream_source_id) VALUES (1,10,1),(2,100,2),(3,100,3);
INSERT INTO theme_types (id,name) VALUES (1,'OP');
INSERT INTO themes (id,anime_id,theme_type_id) VALUES (1,1,1);
INSERT INTO theme_segments (id,theme_id,fansub_group_id,version,start_episode,end_episode,source_type,source_ref)
 VALUES (1,1,1,'v1',1,1,'release_asset',''),
        (2,1,2,'v99',99,100,'release_asset','assigned-outside-range'),
        (3,1,2,'v2',50,50,'release_asset','   ');
INSERT INTO theme_segment_assignments (theme_segment_id,release_version_id) VALUES (2,10),(3,11);
-- 164-01: filler/episode-type lookup tables do not exist in the shared Phase-117
-- prerequisites, so publicEpisodeQuery's new LEFT JOINs need them added here.
-- Episode 11 gets an explicit classification (filler/ova); episode 14 stays
-- unclassified (NULL/NULL) to exercise the COALESCE('unknown')/('episode') fallback.
ALTER TABLE episodes ADD COLUMN filler_type_id BIGINT, ADD COLUMN episode_type_id BIGINT;
-- 164-10 GAP-11: label column mirrors migration 0169's backfill exactly, so the
-- new eft.label/et.label SELECT columns resolve to real values in this fixture too.
CREATE TABLE episode_filler_types (id BIGINT PRIMARY KEY, name TEXT NOT NULL, label TEXT);
INSERT INTO episode_filler_types (id,name,label) VALUES
 (1,'unknown','Unbekannt'),(2,'canon','Haupthandlung'),(3,'filler','Zusatzfolge'),(4,'mixed','Teilweise Zusatzfolge'),(5,'recap','Rückblick');
CREATE TABLE episode_types (id BIGINT PRIMARY KEY, name TEXT NOT NULL, label TEXT);
INSERT INTO episode_types (id,name,label) VALUES
 (1,'episode','Episode'),(2,'special','Special'),(3,'ova','OVA'),(4,'ona','ONA'),(5,'movie','Movie'),
 (6,'recap','Recap'),(7,'preview','Preview'),(8,'prologue','Prologue'),(9,'epilogue','Epilogue'),(10,'bonus','Bonus');
ALTER TABLE episodes ADD CONSTRAINT fk_episodes_filler_type FOREIGN KEY (filler_type_id) REFERENCES episode_filler_types(id);
ALTER TABLE episodes ADD CONSTRAINT fk_episodes_episode_type FOREIGN KEY (episode_type_id) REFERENCES episode_types(id);
UPDATE episodes SET filler_type_id=3, episode_type_id=3 WHERE id=11;
-- 164-01: group/logo COALESCE alignment (loadReleaseGroups parity) + batched
-- has_images/has_notes/has_karaoke flags fixture, minimal columns per
-- project_member_public_repository_episodes_integration_test.go's precedent.
-- Scoped to release_version_id=10 (variant 100, "First release"): one approved
-- public screenshot + one published public note. release_version_id=11 (variant
-- 101) deliberately gets neither, to prove the false/false case.
ALTER TABLE fansub_groups ADD COLUMN logo_id BIGINT REFERENCES media_assets(id);
CREATE TABLE review_statuses (id BIGSERIAL PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE);
INSERT INTO review_statuses (code) VALUES ('approved');
ALTER TABLE media_assets ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ready',
 ADD COLUMN visibility_id BIGINT REFERENCES visibilities(id),
 ADD COLUMN review_status_id BIGINT REFERENCES review_statuses(id);
CREATE TABLE release_version_media (
 id BIGINT PRIMARY KEY,
 release_version_id BIGINT NOT NULL REFERENCES release_versions(id),
 media_asset_id BIGINT NOT NULL REFERENCES media_assets(id),
 category VARCHAR(30) NOT NULL,
 deleted_at TIMESTAMPTZ
);
INSERT INTO media_assets (id,file_path,status,visibility_id,review_status_id) VALUES
 (900,'/media/fixture-screenshot.png','ready',(SELECT id FROM visibilities WHERE name='public'),(SELECT id FROM review_statuses WHERE code='approved'));
INSERT INTO release_version_media (id,release_version_id,media_asset_id,category) VALUES (900,10,900,'screenshot');
INSERT INTO members (id,nickname,display_name) VALUES (900,'fixture-member','Fixture Member');
INSERT INTO release_version_notes (id,release_version_id,member_id,visibility,status) VALUES (900,10,900,'public','published');
-- 164-08 GAP-01: group 1 gets a media-asset logo whose file_path is a server path, not a
-- web URL (the exact bug shape). Group 2 keeps a directly-stored, already-correct web URL
-- (regression: must pass through verbatim). Group 3 has neither and is attached to
-- release_version 11 (variant 101) alongside group 2, to prove the "no logo at all" case
-- emits no fallback value.
INSERT INTO media_assets (id,file_path) VALUES (901,'/app/media/logo_fixture.png');
UPDATE fansub_groups SET logo_id=901 WHERE id=1;
UPDATE fansub_groups SET logo_url='/api/v1/media/files/existing-logo.png' WHERE id=2;
INSERT INTO fansub_groups (id,slug,name) VALUES (3,'stored-three','Third group');
INSERT INTO release_version_groups VALUES (11,3);
-- 164-08 GAP-02: dedicated anime=9 fixture proving publicEpisodeQuery's release_name
-- field. All four release_versions hang off the same episode/fansub_release so a
-- single request exercises every Test 1-5 case at once. Release 9001's title equals
-- its own release_variants.filename (Test 1/4); 9002's title is empty (Test 2);
-- 9003's title is a genuine group-entered title (Test 3); 9004's title is NULL and
-- carries two groups (Test 5, coop).
INSERT INTO anime (id,status) VALUES (9,'done');
INSERT INTO episodes (id,anime_id,episode_number,title) VALUES (901,9,'1','Gap Zwei Episode');
INSERT INTO fansub_groups (id,slug,name) VALUES
 (91,'gap-solo','Solo Gruppe'),(92,'gap-coop-a','Coop Gruppe A'),(93,'gap-coop-b','Coop Gruppe B');
INSERT INTO fansub_releases (id,episode_id) VALUES (901,901);
INSERT INTO release_versions (id,release_id,version,title) VALUES
 (9001,901,'v1','Naruto.S01E01-AnimeOwnage.avi'),
 (9002,901,'v1',''),
 (9003,901,'v1','Special Edition'),
 (9004,901,'v1',NULL);
INSERT INTO release_variants (id,release_version_id,video_quality,subtitle_type,filename) VALUES
 (9001,9001,'1080p','softsub','Naruto.S01E01-AnimeOwnage.avi'),
 (9002,9002,'1080p','softsub','other-file.mkv'),
 (9003,9003,'1080p','softsub','not-matching.mkv'),
 (9004,9004,'1080p','softsub','coop-file.mkv');
INSERT INTO release_version_groups VALUES (9001,91),(9002,91),(9003,91),(9004,92),(9004,93);
`)
	require.NoError(t, err)
	testsupport.ApplySQLFile(t, fixture, filepath.Join("..", "..", "..", "database", "migrations", "0166_jellyfin_source_identity.up.sql"))
	tr := &episodePublicTracer{}
	cfg := fixture.Config()
	cfg.ConnConfig.Tracer = tr
	cfg.MaxConns = 1
	pool, err := pgxpool.NewWithConfig(context.Background(), cfg)
	require.NoError(t, err)
	t.Cleanup(pool.Close)
	require.NoError(t, pool.Ping(context.Background()))
	tr.reset()
	return pool, tr
}

type publicEpisodeFixture struct {
	EpisodeID        int64            `json:"episode_id"`
	EpisodeNumber    int32            `json:"episode_number"`
	EpisodeTitle     string           `json:"episode_title"`
	VersionCount     int              `json:"version_count"`
	DefaultVersionID *int64           `json:"default_version_id"`
	Versions         []map[string]any `json:"versions"`
	FillerType       string           `json:"filler_type"`
	EpisodeType      string           `json:"episode_type"`
	FillerTypeLabel  string           `json:"filler_type_label"`
	EpisodeTypeLabel string           `json:"episode_type_label"`
}
type publicEpisodeEnvelope struct {
	Data struct {
		AnimeID    int64                  `json:"anime_id"`
		Episodes   []publicEpisodeFixture `json:"episodes"`
		Pagination struct {
			HasMore    bool    `json:"has_more"`
			NextCursor *string `json:"next_cursor"`
			RowLimit   int     `json:"row_limit"`
		} `json:"pagination"`
	} `json:"data"`
}

func episodePublicRequest(t *testing.T, pool *pgxpool.Pool, path string, status int) ([]byte, publicEpisodeEnvelope) {
	t.Helper()
	gin.SetMode(gin.TestMode)
	h := handlers.NewFansubHandler(repository.NewFansubRepository(pool), repository.NewEpisodeVersionRepository(pool), nil, "admin", handlers.FansubProxyConfig{})
	router := gin.New()
	router.GET("/anime/:id/episodes", h.ListGroupedEpisodes)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, httptest.NewRequest("GET", path, nil))
	require.Equal(t, status, w.Code, w.Body.String())
	var result publicEpisodeEnvelope
	if status == 200 {
		require.NoError(t, json.Unmarshal(w.Body.Bytes(), &result))
	}
	return w.Body.Bytes(), result
}
func assertPublicBudget(t *testing.T, tr *episodePublicTracer, limit int) {
	t.Helper()
	require.Len(t, tr.queries, 3, "existence plus one bounded query plus one batched has_images/has_notes/has_karaoke flags query")
	require.EqualValues(t, 1, tr.queries[0].Rows)
	require.LessOrEqual(t, tr.queries[1].Rows, int64(limit+1))
	require.NotContains(t, tr.queries[1].SQL, "theme_segment")
	require.NotContains(t, tr.queries[1].SQL, "release_streams")
	t.Logf("SQL statements=%d returned rows=%d+%d (inventory budget %d+1)", len(tr.queries), tr.queries[0].Rows, tr.queries[1].Rows, limit)
}

// assertPublicBudgetEmptyResult covers the zero-release_version_ids case (164-01
// Task 2 behavior): resolvePublicEpisodeFlags must not run at all when the page has
// no versions, so the budget stays at 2 (existence + main query), not 3.
func assertPublicBudgetEmptyResult(t *testing.T, tr *episodePublicTracer) {
	t.Helper()
	require.Len(t, tr.queries, 2, "existence plus one bounded query; zero release_version_ids must skip the flags query entirely")
	require.EqualValues(t, 1, tr.queries[0].Rows)
}

// publicFansubGroupByID locates the group entry with the given id inside a decoded
// fansub_groups JSON array (map[string]any, generic per-envelope decoding, see
// publicEpisodeEnvelope). Fails the test if no such group is present.
func publicFansubGroupByID(t *testing.T, raw any, id int64) map[string]any {
	t.Helper()
	groups, ok := raw.([]any)
	require.True(t, ok, "fansub_groups must decode as a JSON array")
	for _, entry := range groups {
		group, ok := entry.(map[string]any)
		require.True(t, ok)
		if int64(group["id"].(float64)) == id {
			return group
		}
	}
	t.Fatalf("group id=%d not found in fansub_groups", id)
	return nil
}

// publicFansubGroupField reads a single string field off the group with the given id.
func publicFansubGroupField(t *testing.T, raw any, id int64, field string) string {
	t.Helper()
	value, ok := publicFansubGroupByID(t, raw, id)[field].(string)
	require.True(t, ok, "field %q must be a non-null string on group id=%d", field, id)
	return value
}

func TestEpisodeVersionPublicMixedAndIdentity(t *testing.T) {
	pool, tr := openEpisodeVersionPublicFixture(t)
	raw, page := episodePublicRequest(t, pool, "/anime/1/episodes?projection=public", 200)
	require.Equal(t, 24, page.Data.Pagination.RowLimit)
	require.False(t, page.Data.Pagination.HasMore)
	require.Nil(t, page.Data.Pagination.NextCursor)
	require.Len(t, page.Data.Episodes, 2, "episodes without any public release (12, 13) must disappear entirely after the fix")
	require.Equal(t, []int64{11, 14}, []int64{page.Data.Episodes[0].EpisodeID, page.Data.Episodes[1].EpisodeID})
	require.Len(t, page.Data.Episodes[0].Versions, 2, "multiple streams/groups cannot fan out variants")
	first := page.Data.Episodes[0].Versions[0]
	require.EqualValues(t, 100, first["id"])
	require.EqualValues(t, 100, first["variant_id"])
	require.EqualValues(t, 10, first["release_version_id"])
	require.Len(t, first["fansub_groups"], 2)
	require.Equal(t, 2, page.Data.Episodes[0].VersionCount)
	// GAP-01 (164-08 Test 1/2): group 1's media_assets.file_path (/app/media/...) must
	// resolve to a web-safe /api/v1/media/files/<basename> URL, never the raw server
	// path; group 2's already-correct fansub_groups.logo_url column must pass through
	// verbatim (regression, no media_assets row involved).
	require.Equal(t, "/api/v1/media/files/logo_fixture.png", publicFansubGroupField(t, first["fansub_groups"], 1, "logo_url"))
	require.Equal(t, "/api/v1/media/files/existing-logo.png", publicFansubGroupField(t, first["fansub_groups"], 2, "logo_url"))
	require.EqualValues(t, 100, *page.Data.Episodes[0].DefaultVersionID)
	equal := page.Data.Episodes[1].Versions[0]
	require.Equal(t, equal["variant_id"], equal["release_version_id"])
	for _, field := range []string{"media_provider", "media_item_id", "stream_url", "segment_count", "has_segment_asset", "duration_seconds", "crc32", "created_at", "updated_at", "covered_episode_numbers"} {
		require.NotContains(t, first, field)
	}
	require.Equal(t, "filler", page.Data.Episodes[0].FillerType, "episode 11 has an explicit filler_type_id")
	require.Equal(t, "ova", page.Data.Episodes[0].EpisodeType, "episode 11 has an explicit episode_type_id")
	require.Equal(t, "unknown", page.Data.Episodes[1].FillerType, "episode 14 has no filler_type_id, must fall back to COALESCE('unknown')")
	require.Equal(t, "episode", page.Data.Episodes[1].EpisodeType, "episode 14 has no episode_type_id, must fall back to COALESCE('episode')")
	// GAP-11 (164-10): the same existing eft/et LEFT JOINs now also resolve the
	// DB-backed display label, with the matching COALESCE fallback for unclassified episodes.
	require.Equal(t, "Zusatzfolge", page.Data.Episodes[0].FillerTypeLabel, "episode 11's filler label must come from episode_filler_types.label")
	require.Equal(t, "OVA", page.Data.Episodes[0].EpisodeTypeLabel, "episode 11's episode-type label must come from episode_types.label")
	require.Equal(t, "Unbekannt", page.Data.Episodes[1].FillerTypeLabel, "episode 14 has no filler_type_id, must fall back to COALESCE('Unbekannt')")
	require.Equal(t, "Episode", page.Data.Episodes[1].EpisodeTypeLabel, "episode 14 has no episode_type_id, must fall back to COALESCE('Episode')")
	require.Equal(t, true, first["has_images"], "release_version_id 10 (variant 100) has an approved public screenshot")
	require.Equal(t, true, first["has_notes"], "release_version_id 10 (variant 100) has a published public note")
	require.Equal(t, false, first["has_karaoke"], "release_version_id 10 (variant 100) has no typesetting_karaoke media")
	second := page.Data.Episodes[0].Versions[1]
	require.EqualValues(t, 11, second["release_version_id"])
	require.Equal(t, false, second["has_images"], "release_version_id 11 (variant 101) has zero fixture image/note rows")
	require.Equal(t, false, second["has_notes"], "release_version_id 11 (variant 101) has zero fixture image/note rows")
	require.Equal(t, false, second["has_karaoke"], "release_version_id 11 (variant 101) has zero fixture image/note rows")
	require.Len(t, second["fansub_groups"], 2, "release_version 11 carries group 2 (URL logo) plus fixture group 3 (no logo at all)")
	require.Equal(t, "/api/v1/media/files/existing-logo.png", publicFansubGroupField(t, second["fansub_groups"], 2, "logo_url"))
	// GAP-01 Test 3: a group with neither logo_id nor logo_url must emit no usable
	// logo_url at all (omitempty drops the key rather than serializing a placeholder).
	thirdGroup := publicFansubGroupByID(t, second["fansub_groups"], 3)
	require.NotContains(t, thirdGroup, "logo_url", "a group without any logo source must not emit a logo_url key")
	assertPublicBudget(t, tr, 24)
	t.Logf("mixed payload bytes=%d", len(raw))
	tr.reset()
	_, foreign := episodePublicRequest(t, pool, "/anime/6/episodes?projection=public", 200)
	require.EqualValues(t, 10, foreign.Data.Episodes[0].Versions[0]["variant_id"])
	require.EqualValues(t, 20, foreign.Data.Episodes[0].Versions[0]["release_version_id"])
	assertPublicBudget(t, tr, 24)
}

func TestEpisodeVersionPublicAtomicPages(t *testing.T) {
	pool, tr := openEpisodeVersionPublicFixture(t)
	for _, limit := range []int{1, 24, 100} {
		t.Run(fmt.Sprint(limit), func(t *testing.T) {
			seen := map[string]bool{}
			cursor := ""
			pages := 0
			totalBytes := 0
			for {
				tr.reset()
				raw, page := episodePublicRequest(t, pool, fmt.Sprintf("/anime/4/episodes?projection=public&limit=%d&cursor=%s", limit, url.QueryEscape(cursor)), 200)
				rows := 0
				for _, episode := range page.Data.Episodes {
					if episode.EpisodeID == 41 {
						require.Equal(t, 125, episode.VersionCount)
						require.EqualValues(t, 1000, *episode.DefaultVersionID)
					}
					require.NotEmpty(t, episode.Versions, "public projection must never return a neutral (versionless) episode row")
					for _, variant := range episode.Versions {
						key := fmt.Sprintf("%d:%.0f", episode.EpisodeID, variant["variant_id"])
						require.False(t, seen[key])
						seen[key] = true
						rows++
					}
				}
				require.LessOrEqual(t, rows, limit)
				assertPublicBudget(t, tr, limit)
				pages++
				totalBytes += len(raw)
				if !page.Data.Pagination.HasMore {
					require.Nil(t, page.Data.Pagination.NextCursor)
					break
				}
				require.NotNil(t, page.Data.Pagination.NextCursor)
				require.NotEmpty(t, *page.Data.Pagination.NextCursor)
				require.NotEqual(t, cursor, *page.Data.Pagination.NextCursor)
				cursor = *page.Data.Pagination.NextCursor
				require.LessOrEqual(t, pages, 126)
			}
			require.Len(t, seen, 125)
			require.False(t, seen["42:0"], "episode 42 has zero releases and must not appear at all after the fix")
			t.Logf("limit=%d pages=%d atomic rows=%d total serialized bytes=%d", limit, pages, len(seen), totalBytes)
		})
	}
	tr.reset()
	_, first := episodePublicRequest(t, pool, "/anime/1/episodes?projection=public&limit=1", 200)
	require.NotNil(t, first.Data.Pagination.NextCursor)
	cursor := *first.Data.Pagination.NextCursor
	tr.reset()
	episodePublicRequest(t, pool, "/anime/4/episodes?projection=public&cursor="+url.QueryEscape(cursor), 400)
	require.Empty(t, tr.queries, "foreign anime cursor must fail before SQL")
}

func TestEpisodeVersionPublicEmptyAndVisibility(t *testing.T) {
	pool, tr := openEpisodeVersionPublicFixture(t)
	_, empty := episodePublicRequest(t, pool, "/anime/2/episodes?projection=public", 200)
	require.NotNil(t, empty.Data.Episodes)
	require.Empty(t, empty.Data.Episodes)
	require.False(t, empty.Data.Pagination.HasMore)
	assertPublicBudgetEmptyResult(t, tr)
	tr.reset()
	_, neutral := episodePublicRequest(t, pool, "/anime/5/episodes?projection=public", 200)
	require.Empty(t, neutral.Data.Episodes, "anime 5's only episode has zero releases and must not appear after the fix")
	assertPublicBudgetEmptyResult(t, tr)
	for _, id := range []int{3, 999} {
		tr.reset()
		episodePublicRequest(t, pool, fmt.Sprintf("/anime/%d/episodes?projection=public", id), 404)
		require.Len(t, tr.queries, 1)
	}
}

// TestEpisodeVersionPublicFullAssignmentAndWrites, TestEpisodeVersionPublicRawQueryCompatibility,
// and TestEpisodeVersionPublicReleaseNameDefaultFormat moved to
// episode_version_public_writes_test.go (164-10, CLAUDE.md's 450-line production-file cap).
