package repository

import (
 "context"
 "encoding/json"
 "testing"
 "github.com/jackc/pgx/v5"
 "github.com/jackc/pgx/v5/pgxpool"
 "github.com/stretchr/testify/require"
 "team4s.v3/backend/internal/models"
 "team4s.v3/backend/internal/testsupport"
)

// Reuses the explicit dedicated-database guard and unique-schema cleanup.
// This fixture never reads DATABASE_URL or creates application data.
func openJellyfinSourceFixture(t *testing.T) *pgxpool.Pool {
 t.Helper()
 pool := testsupport.OpenPhase117Postgres(t)
 _, err := pool.Exec(context.Background(), `
 ALTER TABLE stream_sources ADD COLUMN metadata JSONB NOT NULL DEFAULT '{}';
 ALTER TABLE stream_sources ADD CONSTRAINT jellyfin_fixture_identity UNIQUE(provider_type, external_id);
 ALTER TABLE stream_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
 `)
 require.NoError(t,err)
 return pool
}

func sourceFixtureSnapshot(id, path string, complete bool) models.JellyfinSourceSnapshot {
 index := int32(1)
 return models.JellyfinSourceSnapshot{Version:1, MediaSourceID:id, SourcePath:path, StreamsComplete:complete,
 SelectedAudioIndex:&index, AudioTracks:[]models.JellyfinAudioTrack{{Index:1,Codec:"flac"}},
 SubtitleTracks:[]models.JellyfinSubtitleTrack{{Index:2,Codec:"ass"}}}
}

func TestJellyfinSourceRepositoryNamespaceAndRetention(t *testing.T) {
 pool:=openJellyfinSourceFixture(t); ctx:=context.Background()
 a:=sourceFixtureSnapshot("source-a","/anime/a.mkv",true)
 tx,err:=pool.Begin(ctx);require.NoError(t,err);defer tx.Rollback(ctx)
 id,err:=upsertStreamSourceSnapshot(ctx,tx,"jellyfin","item",nil,&a);require.NoError(t,err)
 require.NoError(t,tx.Commit(ctx))
 _,err=pool.Exec(ctx,`UPDATE stream_sources SET metadata=metadata || '{"other":{"kept":true}}'::jsonb WHERE id=$1`,id);require.NoError(t,err)
 repo:=NewEpisodeImportRepository(pool)
 bindings,err:=repo.GetJellyfinSourceBindings(ctx,[]string{"item","absent"});require.NoError(t,err)
 require.Len(t,bindings,1);require.Equal(t,a,bindings["item"])
 for _, next:=range []models.JellyfinSourceSnapshot{
  {Version:1,MediaSourceID:"source-a",SourcePath:"/anime/a.mkv"},
  {Version:1,MediaSourceID:"rescanned-a",SourcePath:"/anime/a.mkv"},
 } {
  tx,err=pool.Begin(ctx);require.NoError(t,err)
  sameID,writeErr:=upsertStreamSourceSnapshot(ctx,tx,"jellyfin","item",nil,&next);require.NoError(t,writeErr);require.Equal(t,id,sameID)
  require.NoError(t,tx.Commit(ctx))
 }
 var raw []byte
 require.NoError(t,pool.QueryRow(ctx,`SELECT metadata FROM stream_sources WHERE id=$1`,id).Scan(&raw))
 var metadata map[string]json.RawMessage; require.NoError(t,json.Unmarshal(raw,&metadata));require.Contains(t,metadata,"other")
 var stored models.JellyfinSourceSnapshot;require.NoError(t,json.Unmarshal(metadata["jellyfin_source"],&stored))
 require.True(t,stored.StreamsComplete);require.Equal(t,a.AudioTracks,stored.AudioTracks);require.Equal(t,a.SubtitleTracks,stored.SubtitleTracks)
 require.Equal(t,"rescanned-a",stored.MediaSourceID)
}

func TestJellyfinSourceRepositoryRejectsDifferentIncompleteAndStaleBinding(t *testing.T) {
 pool:=openJellyfinSourceFixture(t);ctx:=context.Background()
 a:=sourceFixtureSnapshot("source-a","/anime/a.mkv",true)
 tx,err:=pool.Begin(ctx);require.NoError(t,err)
 _,err=upsertStreamSourceSnapshot(ctx,tx,"jellyfin","item",nil,&a);require.NoError(t,err);require.NoError(t,tx.Commit(ctx))
 for _,tc:=range []struct{item string; next models.JellyfinSourceSnapshot}{
  {"item",sourceFixtureSnapshot("source-b","/anime/b.mkv",false)},
  {"new-item",sourceFixtureSnapshot("source-b","/anime/b.mkv",false)},
  {"item",sourceFixtureSnapshot("source-b","/anime/b.mkv",true)},
 } {
  tx,err=pool.Begin(ctx);require.NoError(t,err)
  _,err=upsertStreamSourceSnapshot(ctx,tx,"jellyfin",tc.item,nil,&tc.next);require.ErrorIs(t,err,ErrConflict)
  require.NoError(t,tx.Rollback(ctx))
 }
 var count int;require.NoError(t,pool.QueryRow(ctx,"SELECT count(*) FROM stream_sources").Scan(&count));require.Equal(t,1,count)
 bindings,err:=NewEpisodeImportRepository(pool).GetJellyfinSourceBindings(ctx,[]string{"item"});require.NoError(t,err);require.Equal(t,a,bindings["item"])
}

// The second writer observes the committed binding while holding its row lock.
func TestJellyfinSourceRepositoryLockedBinding(t *testing.T) {
 pool:=openJellyfinSourceFixture(t);ctx:=context.Background()
 a:=sourceFixtureSnapshot("a","/anime/a",true)
 tx,err:=pool.Begin(ctx);require.NoError(t,err)
 id,err:=upsertStreamSourceSnapshot(ctx,tx,"jellyfin","item",nil,&a);require.NoError(t,err);require.NoError(t,tx.Commit(ctx))
 tx,err=pool.Begin(ctx);require.NoError(t,err)
 b:=sourceFixtureSnapshot("b","/anime/b",true); raw,err:=json.Marshal(b);require.NoError(t,err)
 _,err=tx.Exec(ctx,`UPDATE stream_sources SET metadata=jsonb_build_object('jellyfin_source',$1::jsonb) WHERE id=$2`,raw,id);require.NoError(t,err)
 result:=make(chan error,1)
 go func(){ nextTx,beginErr:=pool.BeginTx(ctx,pgx.TxOptions{});if beginErr!=nil{result<-beginErr;return};defer nextTx.Rollback(ctx);_,writeErr:=upsertStreamSourceSnapshot(ctx,nextTx,"jellyfin","item",nil,&a);result<-writeErr }()
 require.NoError(t,tx.Commit(ctx));require.ErrorIs(t,<-result,ErrConflict)
}
