package repository_test

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http/httptest"
	"sync"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/require"
	"team4s.v3/backend/internal/handlers"
	"team4s.v3/backend/internal/repository"
	"team4s.v3/backend/internal/testsupport"
)

type episodePublicQuery struct {
	SQL  string
	Rows int64
}
type episodePublicTracer struct {
	mu      sync.Mutex
	queries []*episodePublicQuery
}
type episodePublicTraceKey struct{}

func (tr *episodePublicTracer) TraceQueryStart(ctx context.Context, _ *pgx.Conn, d pgx.TraceQueryStartData) context.Context {
	q := &episodePublicQuery{SQL: d.SQL}
	tr.mu.Lock()
	tr.queries = append(tr.queries, q)
	tr.mu.Unlock()
	return context.WithValue(ctx, episodePublicTraceKey{}, q)
}
func (tr *episodePublicTracer) TraceQueryEnd(ctx context.Context, _ *pgx.Conn, d pgx.TraceQueryEndData) {
	tr.mu.Lock()
	defer tr.mu.Unlock()
	ctx.Value(episodePublicTraceKey{}).(*episodePublicQuery).Rows = d.CommandTag.RowsAffected()
}
func (tr *episodePublicTracer) reset() { tr.mu.Lock(); defer tr.mu.Unlock(); tr.queries = nil }

func openEpisodeVersionPublicFixture(t *testing.T) (*pgxpool.Pool, *episodePublicTracer) {
	t.Helper()
	// Explicit guarded test DSN, unique schema/search_path and scoped cleanup;
	// never application DATABASE_URL. Schema additions exist only in this fixture.
	fixture := testsupport.OpenPhase117Postgres(t)
	_, err := fixture.Exec(context.Background(), `
ALTER TABLE anime ADD COLUMN status TEXT NOT NULL DEFAULT 'done';
ALTER TABLE fansub_groups ADD COLUMN slug TEXT, ADD COLUMN logo_url TEXT;
ALTER TABLE fansub_releases ADD COLUMN source_id BIGINT, ADD COLUMN source BIGINT,
    ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE release_versions ADD COLUMN production_started_on TIMESTAMPTZ,
    ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE release_variants ADD COLUMN video_quality TEXT, ADD COLUMN resolution TEXT,
    ADD COLUMN subtitle_type TEXT, ADD COLUMN crc32 TEXT, ADD COLUMN filename TEXT, ADD COLUMN container TEXT,
    ADD COLUMN video_codec TEXT, ADD COLUMN audio_codec TEXT, ADD COLUMN created_at TIMESTAMPTZ DEFAULT NOW(),
    ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW();
CREATE TABLE release_variant_episodes (release_variant_id BIGINT REFERENCES release_variants(id),
    episode_id BIGINT REFERENCES episodes(id), position INT, PRIMARY KEY(release_variant_id, episode_id));
CREATE TABLE release_sources (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT, source_type TEXT, type TEXT);
CREATE TABLE stream_types (id BIGINT PRIMARY KEY, name TEXT);
INSERT INTO stream_types VALUES (1, 'episode');
ALTER TABLE release_streams ADD COLUMN stream_type_id BIGINT DEFAULT 1, ADD COLUMN audio_language_id BIGINT,
    ADD COLUMN subtitle_language_id BIGINT, ADD COLUMN modified_at TIMESTAMPTZ DEFAULT NOW(), ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE stream_sources ADD CONSTRAINT fixture_stream_source_identity UNIQUE(provider_type, external_id);
ALTER TABLE fansub_releases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 10000);
ALTER TABLE release_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 20000);
ALTER TABLE release_variants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 30000);
ALTER TABLE stream_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 40000);
ALTER TABLE release_streams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 50000);
INSERT INTO anime (id,status) VALUES (1,'done'),(2,'done'),(3,'disabled'),(4,'done'),(5,'done'),(6,'done');
INSERT INTO episodes (id,anime_id,episode_number,title) VALUES
 (11,1,'1','Episode one'),(12,1,'2','Neutral mixed'),(13,1,'1','Same number, another neutral episode'),
 (14,1,'3','Equal IDs'),(41,4,'1','Many variants'),(42,4,'2','Neutral after many'),(51,5,'1','Only neutral'),(61,6,'1','Foreign');
INSERT INTO fansub_groups (id,slug,name) VALUES (1,'stored-one','First group'),(2,'stored-two','Second group');
INSERT INTO fansub_releases (id,episode_id) VALUES (1,11),(2,14),(3,13),(4,41),(6,61);
INSERT INTO release_versions (id,release_id,version,title,production_started_on,release_date) VALUES
 (10,1,'v1','First release','2020-01-01','2020-02-01'),(11,1,'v2','Second release',NULL,'2021-02-01'),
 (13,3,'v1','No variant',NULL,NULL),(200,2,'v1','Equal ID release',NULL,NULL),
 (40,4,'v1','Large release',NULL,NULL),(20,6,'v1','Foreign release',NULL,NULL);
INSERT INTO release_variants (id,release_version_id,video_quality,subtitle_type,crc32,duration_seconds) VALUES
 (100,10,'1080p','softsub','ABCDEF01',1440),(101,11,'720p','hardsub','01234567',1430),
 (200,200,'480p','softsub',NULL,1400),(10,20,'1080p','softsub',NULL,1400);
INSERT INTO release_variants (id,release_version_id,video_quality,subtitle_type)
 SELECT 1000+n,40,'1080p','softsub' FROM generate_series(0,124) n;
INSERT INTO release_variant_episodes SELECT rv.id,fr.episode_id,1 FROM release_variants rv
 JOIN release_versions rev ON rev.id=rv.release_version_id JOIN fansub_releases fr ON fr.id=rev.release_id;
INSERT INTO release_version_groups VALUES (10,1),(10,2),(11,2),(200,1),(40,1),(40,2),(20,2);
INSERT INTO stream_sources (id,provider_type,external_id,url) VALUES
 (1,'jellyfin','foreign','https://fixture.invalid/foreign'),(2,'jellyfin','own','https://fixture.invalid/own'),
 (3,'external','second','https://fixture.invalid/second');
INSERT INTO release_streams (id,variant_id,stream_source_id) VALUES (1,10,1),(2,100,2),(3,100,3);
INSERT INTO theme_types (id,name) VALUES (1,'OP');
INSERT INTO themes (id,anime_id,theme_type_id) VALUES (1,1,1);
INSERT INTO theme_segments (id,theme_id,fansub_group_id,version,start_episode,end_episode,source_type,source_ref)
 VALUES (1,1,1,'v1',1,1,'release_asset',''),
        (2,1,2,'v99',99,100,'release_asset','assigned-outside-range'),
        (3,1,2,'v2',50,50,'release_asset','   ');
INSERT INTO theme_segment_assignments (theme_segment_id,release_version_id) VALUES (2,10),(3,11);
`)
	require.NoError(t, err)
	tr := &episodePublicTracer{}
	cfg := fixture.Config()
	cfg.ConnConfig.Tracer = tr
	cfg.MaxConns = 1
	pool, err := pgxpool.NewWithConfig(context.Background(), cfg)
	require.NoError(t, err)
	t.Cleanup(pool.Close)
	require.NoError(t, pool.Ping(context.Background()))
	tr.reset()
	return pool, tr
}

type publicEpisodeFixture struct {
	EpisodeID        int64            `json:"episode_id"`
	EpisodeNumber    int32            `json:"episode_number"`
	EpisodeTitle     string           `json:"episode_title"`
	VersionCount     int              `json:"version_count"`
	DefaultVersionID *int64           `json:"default_version_id"`
	Versions         []map[string]any `json:"versions"`
}
type publicEpisodeEnvelope struct {
	Data struct {
		AnimeID    int64                  `json:"anime_id"`
		Episodes   []publicEpisodeFixture `json:"episodes"`
		Pagination struct {
			HasMore    bool    `json:"has_more"`
			NextCursor *string `json:"next_cursor"`
			RowLimit   int     `json:"row_limit"`
		} `json:"pagination"`
	} `json:"data"`
}

func episodePublicRequest(t *testing.T, pool *pgxpool.Pool, path string, status int) ([]byte, publicEpisodeEnvelope) {
	t.Helper()
	gin.SetMode(gin.TestMode)
	h := handlers.NewFansubHandler(repository.NewFansubRepository(pool), repository.NewEpisodeVersionRepository(pool), nil, "admin", handlers.FansubProxyConfig{})
	router := gin.New()
	router.GET("/anime/:id/episodes", h.ListGroupedEpisodes)
	w := httptest.NewRecorder()
	router.ServeHTTP(w, httptest.NewRequest("GET", path, nil))
	require.Equal(t, status, w.Code, w.Body.String())
	var result publicEpisodeEnvelope
	if status == 200 {
		require.NoError(t, json.Unmarshal(w.Body.Bytes(), &result))
	}
	return w.Body.Bytes(), result
}
func assertPublicBudget(t *testing.T, tr *episodePublicTracer, limit int) {
	t.Helper()
	require.Len(t, tr.queries, 2, "existence plus one bounded query, including any metadata SQL")
	require.EqualValues(t, 1, tr.queries[0].Rows)
	require.LessOrEqual(t, tr.queries[1].Rows, int64(limit+1))
	require.NotContains(t, tr.queries[1].SQL, "theme_segment")
	require.NotContains(t, tr.queries[1].SQL, "release_streams")
	t.Logf("SQL statements=%d returned rows=%d+%d (inventory budget %d+1)", len(tr.queries), tr.queries[0].Rows, tr.queries[1].Rows, limit)
}

func TestPhase159FullBaselineBudget(t *testing.T) {
 pool, tr := openEpisodeVersionPublicFixture(t)
 for _, id := range []int{1,4,5,2} {
  tr.reset()
  raw, _ := episodePublicRequest(t,pool,fmt.Sprintf("/anime/%d/episodes",id),200)
  var rows int64
  for _, query := range tr.queries { rows += query.Rows }
  t.Logf("FULL anime=%d statements=%d returned_rows=%d serialized_bytes=%d",id,len(tr.queries),rows,len(raw))
 }
}
