ALTER TABLE anime
    ADD COLUMN IF NOT EXISTS content_type TEXT NOT NULL DEFAULT 'anime',
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ongoing',
    ADD COLUMN IF NOT EXISTS max_episodes SMALLINT,
    ADD COLUMN IF NOT EXISTS source TEXT;
